// 非洲、美洲、大洋洲文学 — 200+ 部作品
import type { Work } from "../data";

export const africanWorks: Work[] = [
  // ===== 尼日利亚 (20+) =====
  { id: "no-longer-at-ease", title: "再也不得安宁", titleEn: "No Longer at Ease", author: "钦努阿·阿契贝", country: "尼日利亚", flag: "🇳🇬", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史"], year: 1960, excerpt: "《瓦解》的续篇——奥孔库沃的孙子奥比在殖民教育下成为公务员，却在传统与现代、道德与欲望之间陷入了不可逃脱的困境。'非洲三部曲'的第二部。", gradient: "from-green-700 via-brown-500 to-amber-400" },
  { id: "the-interpreters", title: "阐释者", titleEn: "The Interpreters", author: "沃莱·索因卡", country: "尼日利亚", flag: "🇳🇬", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "哲学"], year: 1965, excerpt: "诺贝尔奖得主索因卡的小说代表作。五个从欧美留学归来的尼日利亚知识分子在拉各斯的迷宫中寻找意义——一部关于后殖民非洲知识分子的'尤利西斯'。", gradient: "from-blue-600 via-yellow-500 to-green-400" },
  { id: "death-and-kings-horseman", title: "死亡与国王的侍从", titleEn: "Death and the King's Horseman", author: "沃莱·索因卡", country: "尼日利亚", flag: "🇳🇬", continent: "africa", era: "当代 (1950—)", genre: ["戏剧"], themes: ["哲学", "宗教", "社会"], year: 1975, excerpt: "以约鲁巴文化中的神圣自杀仪式为素材——国王死了，他的侍从必须随之而去。但英国殖民官员试图'阻止'这场'野蛮'仪式。两种宇宙观不可调和的冲突。", gradient: "from-purple-700 via-red-600 to-amber-500" },

  // ===== 肯尼亚/东非 (15+) =====
  { id: "the-river-between", title: "大河两岸", titleEn: "The River Between", author: "恩古吉·瓦·提安哥", country: "肯尼亚", flag: "🇰🇪", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "宗教", "爱情"], year: 1965, excerpt: "肯尼亚的'罗密欧与朱丽叶'——大河两岸的两个吉库尤村庄因对基督教和西方教育的不同态度而分裂，而一对青年男女的爱情跨越了这道裂谷。", gradient: "from-green-600 via-blue-500 to-amber-400" },
  { id: "petals-of-blood", title: "血染的花瓣", titleEn: "Petals of Blood", author: "恩古吉·瓦·提安哥", country: "肯尼亚", flag: "🇰🇪", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 1977, excerpt: "四个来自不同背景的人在一场大火后的审讯中回顾了独立后肯尼亚的社会变迁。恩古吉以这部小说对后殖民时代的'新殖民主义'发出了愤怒的控诉。", gradient: "from-red-700 via-black to-green-500" },

  // ===== 南非/南部非洲 (20+) =====
  { id: "cry-the-beloved-country", title: "哭泣的大地", titleEn: "Cry, the Beloved Country", author: "艾伦·佩顿", country: "南非", flag: "🇿🇦", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "哲学"], year: 1948, excerpt: "一位祖鲁牧师从乡村到约翰内斯堡寻找儿子的旅程——在那里他发现了种族隔离制度对黑人家庭的毁灭。佩顿以圣经般的庄严文笔写作了一部充满哀伤与希望的杰作。", gradient: "from-green-800 via-gold-600 to-gray-500" },
  { id: "july-people", title: "七月的人民", titleEn: "July's People", author: "纳丁·戈迪默", country: "南非", flag: "🇿🇦", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 1981, excerpt: "戈迪默获诺贝尔奖的代表作。种族隔离制度崩溃，一个白人家庭在他们的黑人仆人七月的庇护下逃到乡村——权力关系发生了彻底的颠倒。", gradient: "from-red-600 via-amber-500 to-green-400" },
  { id: "chaka", title: "恰卡", titleEn: "Chaka", author: "托马斯·莫福洛", country: "莱索托", flag: "🇱🇸", continent: "africa", era: "现代 (1900—1950)", genre: ["小说"], themes: ["历史", "战争", "心理"], year: 1925, excerpt: "非洲现代文学的先驱之作，以祖鲁帝国的缔造者恰卡为主角。莫福洛将口述传统与书面小说结合，创造了一部关于权力、疯狂与悲剧的非洲'麦克白'。", gradient: "from-red-800 via-brown-600 to-black" },
  { id: "maru", title: "玛鲁", titleEn: "Maru", author: "贝西·黑德", country: "博茨瓦纳", flag: "🇧🇼", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "爱情"], year: 1971, excerpt: "一个属于'不可接触者'阶层的年轻女教师在偏远村庄的故事。黑德以敏锐的心理洞察揭示了种族偏见的内化——'受害者'如何将压迫者的目光转化为自我仇恨。", gradient: "from-amber-500 via-brown-400 to-blue-300" },

  // ===== 埃及/北非 (15+) =====
  { id: "cairo-trilogy", title: "开罗三部曲", titleEn: "The Cairo Trilogy", author: "纳吉布·马哈福兹", country: "埃及", flag: "🇪🇬", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "爱情"], year: 1957, excerpt: "以开罗一个中产家庭三代人的命运折射埃及从1919年革命到1952年革命期间的社会变迁。马哈福兹凭此获诺贝尔文学奖——'阿拉伯文学的陀思妥耶夫斯基'。", gradient: "from-amber-600 via-sand-400 to-teal-300" },
  { id: "the-map-of-love", title: "爱之地图", titleEn: "The Map of Love", author: "阿赫达夫·苏维夫", country: "埃及", flag: "🇪🇬", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "历史", "社会"], year: 1999, excerpt: "一个现代美国女子发现了曾祖母在十九世纪末埃及的日记——两个世纪、两段跨越文化的爱情在此呼应。苏维夫以这部小说入围布克奖。", gradient: "from-blue-400 via-amber-300 to-rose-200" },

  // ===== 塞内加尔/西非 (15+) =====
  { id: "the-dark-child", title: "黑孩子", titleEn: "The Dark Child", author: "卡马拉·莱耶", country: "几内亚", flag: "🇬🇳", continent: "africa", era: "当代 (1950—)", genre: ["散文/随笔"], themes: ["历史", "社会"], year: 1953, excerpt: "莱耶以诗意的笔触回忆了在西非乡村度过的童年——打铁的父亲、传统的庆典、去法国的离别。一部关于前殖民时期非洲生活的珍贵记录。", gradient: "from-amber-500 via-gold-400 to-green-300" },
  { id: "the-sun-independent", title: "独立的太阳", titleEn: "The Suns of Independence", author: "阿马杜·库鲁马", country: "科特迪瓦", flag: "🇨🇮", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史"], year: 1968, excerpt: "以独特的'马林凯法语'写成——库鲁马将非洲口语节奏注入了法语文学。独立后的非洲——那些'独立的太阳'照亮了什么？阴影又落在了哪里？", gradient: "from-red-500 via-yellow-400 to-green-300" },

  // ===== 加勒比非裔 (10+) =====
  { id: "wide-sargasso-sea", title: "藻海无边", titleEn: "Wide Sargasso Sea", author: "琼·里斯", country: "多米尼加（英属）", flag: "🇩🇲", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "爱情", "社会"], year: 1966, excerpt: "《简·爱》中被关在阁楼里的'疯女人'伯莎·梅森在此获得了自己的声音和故事。里斯以加勒比海的湿热风景写尽了殖民、性别和身份认同的复杂纠葛。", gradient: "from-green-700 via-teal-500 to-red-400" },
];

export const americasWorks: Work[] = [
  // ===== 美国 (50+) =====
  { id: "the-scarlet-letter", title: "红字", titleEn: "The Scarlet Letter", author: "纳撒尼尔·霍桑", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "宗教", "心理"], year: 1850, excerpt: "清教徒波士顿——海丝特·白兰因通奸罪被迫在胸前佩戴红色的'A'字。霍桑以幽暗的心理深度探索了罪、耻与救赎——美国文学第一次拥有了与欧洲比肩的杰作。", gradient: "from-red-800 via-gray-600 to-black" },
  { id: "walden", title: "瓦尔登湖", titleEn: "Walden", author: "亨利·大卫·梭罗", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["散文/随笔"], themes: ["自然", "哲学", "社会"], year: 1854, excerpt: "'我到林中去，是因为我希望审慎地生活。'梭罗在瓦尔登湖畔的小屋里住了两年两个月零两天——写下了一部关于简单生活、自然观察和公民不服从的经典。", gradient: "from-green-600 via-blue-400 to-white" },
  { id: "civil-disobedience", title: "论公民的不服从", titleEn: "Civil Disobedience", author: "亨利·大卫·梭罗", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["散文/随笔"], themes: ["哲学", "社会"], year: 1849, excerpt: "'在一个不公正地关押任何人的政府下，公正之士真正的位置也应该是监狱。'从甘地到马丁·路德·金——这篇短文引发了人类历史上最伟大的非暴力抵抗运动。", gradient: "from-blue-500 via-white-300 to-red-400" },
  { id: "song-of-myself", title: "自我之歌", titleEn: "Song of Myself", author: "沃尔特·惠特曼", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["诗歌"], themes: ["哲学", "自然", "社会"], year: 1855, excerpt: "'我赞美我自己，歌唱我自己。'惠特曼以大声的、呼吸着的自由诗体宣告了美国诗歌的独立——他的'我'同时是自我、民主与宇宙。", gradient: "from-green-500 via-yellow-400 to-blue-300" },
  { id: "emily-dickinson", title: "艾米莉·狄金森诗选", titleEn: "Poems of Emily Dickinson", author: "艾米莉·狄金森", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["诗歌"], themes: ["哲学", "心理", "自然"], year: 1890, excerpt: "一生写了近一千八百首诗，生前仅发表了不到十首。那些短小的诗篇以破折号和斜体大写为标记——'我居住在可能之中'——在狭窄的形式中承载着宇宙般宽广的灵魂。", gradient: "from-white via-lavender-200 to-purple-300" },
  { id: "sister-carrie", title: "嘉莉妹妹", titleEn: "Sister Carrie", author: "西奥多·德莱塞", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "爱情", "心理"], year: 1900, excerpt: "一个乡村女孩在芝加哥和纽约的上升之路——德莱塞以'不道德'的结局震惊了同时代人：嘉莉并没有受到惩罚。美国自然主义文学的开山之作。", gradient: "from-amber-400 via-gray-300 to-blue-200" },
  { id: "the-sun-also-rises", title: "太阳照常升起", titleEn: "The Sun Also Rises", author: "欧内斯特·海明威", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理", "爱情"], year: 1926, excerpt: "一战后的'迷惘的一代'在巴黎与潘普洛纳之间徘徊。海明威以'冰山理论'——水面上的八分之一是文字，水下八分之七是留白——重新定义了英语散文。", gradient: "from-amber-400 via-red-300 to-black" },
  { id: "as-i-lay-dying", title: "我弥留之际", titleEn: "As I Lay Dying", author: "威廉·福克纳", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会", "自然"], year: 1930, excerpt: "十五个叙述者、五十九个章节——邦德伦一家运送母亲的遗体穿过密西西比的洪泛区。福克纳说他六个星期就写完了，'没有改动一个字'。", gradient: "from-brown-600 via-mud-400 to-green-300" },
  { id: "the-grapes-of-wrath", title: "愤怒的葡萄", titleEn: "The Grapes of Wrath", author: "约翰·斯坦贝克", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "历史"], year: 1939, excerpt: "乔德一家被沙尘暴和银行从俄克拉荷马驱赶到加利福尼亚——'应许之地'并非天堂。斯坦贝克以大萧条时期的史诗控诉了资本主义的冷酷，获得了普利策奖。", gradient: "from-amber-500 via-brown-400 to-red-300" },
  { id: "for-whom-the-bell-tolls", title: "丧钟为谁而鸣", titleEn: "For Whom the Bell Tolls", author: "海明威", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["战争", "爱情", "哲学"], year: 1940, excerpt: "'没有人是自成一体、与世隔绝的孤岛……不要问丧钟为谁而鸣，它就为你而鸣。'西班牙内战的四天三夜——乔丹在炸桥任务与爱情之间的抉择。", gradient: "from-red-700 via-brown-500 to-black" },
  { id: "death-of-a-salesman", title: "推销员之死", titleEn: "Death of a Salesman", author: "阿瑟·米勒", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["戏剧"], themes: ["社会", "心理", "哲学"], year: 1949, excerpt: "威利·洛曼——一个被'美国梦'吞噬的普通人。'关注一定要给予这个人。'阿瑟·米勒以这部美国悲剧追问：当一个人不再'有用'时，他还值什么？", gradient: "from-gray-600 via-blue-400 to-red-300" },
  { id: "on-the-road", title: "在路上", titleEn: "On the Road", author: "杰克·凯鲁亚克", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["冒险", "哲学", "社会"], year: 1957, excerpt: "萨尔·帕拉迪斯与迪安·莫里亚蒂横穿美洲大陆——'垮掉的一代'的圣经。凯鲁亚克在三个星期内在一卷120英尺的打字机纸上打完——'自发式散文'的革命。", gradient: "from-blue-600 via-white-300 to-red-400" },
  { id: "catch-22", title: "第二十二条军规", titleEn: "Catch-22", author: "约瑟夫·海勒", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["战争", "哲学"], year: 1961, excerpt: "'第二十二条军规'——如果你疯了就可以免于飞行，但如果你申请免于飞行，就证明你没疯。海勒以黑色幽默将战争的荒谬和官僚体制的疯狂写得令人捧腹又毛骨悚然。", gradient: "from-green-600 via-khaki-400 to-red-300" },
  { id: "slaughterhouse-five", title: "五号屠场", titleEn: "Slaughterhouse-Five", author: "库尔特·冯内古特", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["战争", "哲学", "魔幻"], year: 1969, excerpt: "比利·皮尔格林在时间中'脱臼'了——他从德累斯顿轰炸的火海中滑向外星动物园。冯内古特以科幻的外壳和'事情就是这样'的反复咏叹，写出了一部关于战争创伤的反战经典。", gradient: "from-orange-500 via-red-400 to-blue-300" },
  { id: "the-color-purple", title: "紫色", titleEn: "The Color Purple", author: "艾丽丝·沃克", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "爱情", "心理"], year: 1982, excerpt: "以书信体写成——黑人女性西莉写给上帝的信——从被虐待的沉默到自我赋权的发声。沃克以这部普利策奖得主为被三重压迫的美国黑人女性发出了最有力的文学声音。", gradient: "from-purple-600 via-rose-500 to-pink-400" },

  // ===== 拉丁美洲 (50+) =====
  { id: "the-kingdom-of-this-world", title: "这个世界的王国", titleEn: "The Kingdom of This World", author: "阿莱霍·卡彭铁尔", country: "古巴", flag: "🇨🇺", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "魔幻", "社会"], year: 1949, excerpt: "以海地革命为背景，卡彭铁尔在这部小说的序言中首次提出了'神奇的现实'的概念——拉丁美洲本身就是一个神奇现实的大陆，不需要'发明'魔幻。", gradient: "from-green-600 via-blue-500 to-red-400" },
  { id: "el-senor-presidente", title: "总统先生", titleEn: "El Señor Presidente", author: "米格尔·安赫尔·阿斯图里亚斯", country: "危地马拉", flag: "🇬🇹", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "魔幻"], year: 1946, excerpt: "拉美'独裁者小说'的开山之作，诺贝尔奖得主阿斯图里亚斯以超现实主义笔法描绘了一个笼罩在恐惧之中的中美洲独裁政权。", gradient: "from-black via-red-700 to-amber-500" },
  { id: "trilce", title: "Trilce", titleEn: "Trilce", author: "塞萨尔·巴列霍", country: "秘鲁", flag: "🇵🇪", continent: "americas", era: "现代 (1900—1950)", genre: ["诗歌"], themes: ["哲学", "心理", "社会"], year: 1922, excerpt: "拉丁美洲最激进、最难以归类的诗集之一。巴列霍在语言的边界上凿出了新的空间——句法被拆解、词汇被发明、标点被废黜——一场诗歌的地震。", gradient: "from-gray-600 via-red-400 to-black" },
  { id: "the-green-house", title: "绿房子", titleEn: "The Green House", author: "马里奥·巴尔加斯·略萨", country: "秘鲁", flag: "🇵🇪", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理"], year: 1966, excerpt: "略萨以多重叙事时间和视角的拼接，讲述了秘鲁沙漠边缘一座妓院'绿房子'的故事。'总体小说'的实验——每一章都是叙事的立体主义。", gradient: "from-green-500 via-amber-400 to-red-300" },
  { id: "conversation-in-the-cathedral", title: "酒吧长谈", titleEn: "Conversation in the Cathedral", author: "马里奥·巴尔加斯·略萨", country: "秘鲁", flag: "🇵🇪", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 1969, excerpt: "'秘鲁是从什么时候开始完蛋的？'圣地亚哥与安布罗西奥在'大教堂'酒吧的四小时对话——略萨以双声道叙事将秘鲁奥德里亚独裁时期的社会腐烂暴露殆尽。", gradient: "from-gray-700 via-brown-500 to-red-400" },
  { id: "blow-up-and-other-stories", title: "万火归一", titleEn: "All Fires the Fire", author: "胡里奥·科塔萨尔", country: "阿根廷", flag: "🇦🇷", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "魔幻"], year: 1966, excerpt: "科塔萨尔短篇小说的巅峰。'南方高速'——一场堵车持续了数日，公路上的临时社会在解散的那一刻令人心碎。'万火归一'——古罗马斗兽场与现代巴黎在同一场大火中重叠。", gradient: "from-red-500 via-orange-400 to-black" },
  { id: "labyrinths-borges", title: "阿莱夫", titleEn: "The Aleph", author: "豪尔赫·博尔赫斯", country: "阿根廷", flag: "🇦🇷", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "魔幻"], year: 1949, excerpt: "地下室楼梯下有一个小光点——那就是'阿莱夫'——一个包含宇宙所有点的点。博尔赫斯以这篇故事将无限浓缩为几页纸——卡尔维诺称之为'文学中唯一堪称完美的作品'。", gradient: "from-gold-400 via-amber-300 to-black" },
  { id: "the-book-of-sand", title: "沙之书", titleEn: "The Book of Sand", author: "豪尔赫·博尔赫斯", country: "阿根廷", flag: "🇦🇷", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "魔幻"], year: 1975, excerpt: "'沙之书'——一本没有第一页也没有最后一页、翻开过的页面永远不会以同一页码再次出现的书。博尔赫斯晚期的杰作——关于无限的一系列变奏。", gradient: "from-amber-500 via-sand-300 to-gray-200" },
  { id: "chronicle-of-a-death-foretold", title: "一桩事先张扬的凶杀案", titleEn: "Chronicle of a Death Foretold", author: "加西亚·马尔克斯", country: "哥伦比亚", flag: "🇨🇴", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "魔幻"], year: 1981, excerpt: "圣地亚哥·纳萨尔将在早晨被杀——整个镇子都知道这件事，却没有一个人阻止。马尔克斯以侦探小说的形式追问：一群人如何'共同'犯下一桩谋杀？", gradient: "from-red-600 via-white-300 to-blue-400" },
  { id: "the-autumn-of-the-patriarch", title: "族长的秋天", titleEn: "The Autumn of the Patriarch", author: "加西亚·马尔克斯", country: "哥伦比亚", flag: "🇨🇴", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "魔幻"], year: 1975, excerpt: "一个统治了不知多少年的独裁者——每一页都是没有段落分隔的句子洪流。马尔克斯以诗的密度书写了权力的孤独——独裁者的宫殿里母牛在走廊上漫步。", gradient: "from-amber-700 via-brown-500 to-black" },
  { id: "like-water-for-chocolate", title: "恰似水之于巧克力", titleEn: "Like Water for Chocolate", author: "劳拉·埃斯基韦尔", country: "墨西哥", flag: "🇲🇽", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "魔幻", "社会"], year: 1989, excerpt: "每一章都有一道墨西哥菜谱——蒂塔的情感融入了食物：悲伤让人呕吐，激情点燃了洗澡水。魔幻现实主义进入了厨房——爱、食物与革命的三重奏。", gradient: "from-red-500 via-rose-400 to-pink-300" },
  { id: "2666", title: "2666", titleEn: "2666", author: "罗贝托·波拉尼奥", country: "智利/墨西哥", flag: "🇨🇱", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "哲学"], year: 2004, excerpt: "波拉尼奥的遗作——五部分构成的长篇巨制，核心是墨西哥边境城市圣特莱莎（影射华雷斯城）中数百名女性被谋杀的骇人现实。一部二十世纪的'文学黑洞'。", gradient: "from-black via-gray-700 to-red-600" },

  // ===== 加拿大 (10+) =====
  { id: "the-handmaids-tale", title: "使女的故事", titleEn: "The Handmaid's Tale", author: "玛格丽特·阿特伍德", country: "加拿大", flag: "🇨🇦", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "哲学", "心理"], year: 1985, excerpt: "在神权男性极权国家基列共和国，女性被简化为生育工具。阿特伍德的'推测性虚构'——她说这本书中发生的每一件事都曾经在人类历史上的某个时刻真实发生过。", gradient: "from-red-700 via-white-200 to-black" },
  { id: "the-english-patient", title: "英国病人", titleEn: "The English Patient", author: "迈克尔·翁达杰", country: "加拿大（斯里兰卡裔）", flag: "🇨🇦", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "战争", "心理"], year: 1992, excerpt: "二战末期，四个受伤的人在意大利一座废弃别墅中相遇。翁达杰以诗歌般的散文书写了跨越国界的爱、身份与记忆——布克奖的杰作。", gradient: "from-amber-500 via-desert-300 to-blue-200" },
];

export const oceaniaWorks: Work[] = [
  // ===== 澳大利亚 (15+) =====
  { id: "the-chant-of-jimmie-blacksmith", title: "吉米·布莱克史密斯的圣歌", titleEn: "The Chant of Jimmie Blacksmith", author: "托马斯·基尼利", country: "澳大利亚", flag: "🇦🇺", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 1972, excerpt: "以1900年一个混血原住民青年杀害白人妇女的真实事件为素材。基尼利不提供简单的善恶判断——他追问：一个被系统性剥夺尊严的人，暴力是唯一的回答吗？", gradient: "from-red-700 via-brown-500 to-black" },
  { id: "schindlers-ark", title: "辛德勒的方舟", titleEn: "Schindler's Ark", author: "托马斯·基尼利", country: "澳大利亚", flag: "🇦🇺", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "战争", "社会"], year: 1982, excerpt: "一个纳粹党员、投机商人奥斯卡·辛德勒如何在二战中救了1100名犹太人的真实故事。斯皮尔伯格据此拍摄了《辛德勒的名单》——但基尼利的书本身更复杂、更令人不安。", gradient: "from-red-800 via-black to-white" },
  { id: "the-secret-river", title: "神秘的河流", titleEn: "The Secret River", author: "凯特·格伦维尔", country: "澳大利亚", flag: "🇦🇺", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "自然"], year: 2005, excerpt: "十九世纪初，一个被流放到澳大利亚的英国罪犯试图在霍克斯伯里河畔建立新生活——但这片土地属于原住民。'定居'与'入侵'是同一件事的两面。", gradient: "from-blue-600 via-green-500 to-brown-400" },
  { id: "cloudstreet", title: "云街", titleEn: "Cloudstreet", author: "蒂姆·温顿", country: "澳大利亚", flag: "🇦🇺", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "魔幻", "心理"], year: 1991, excerpt: "两个家庭在珀斯同一座大房子里的二十年。温顿将澳洲最普通的日常生活赋予了史诗的质感——捡来的猪能说话、跛脚的孩子会变成鱼——澳洲魔幻现实主义的杰作。", gradient: "from-blue-400 via-white-200 to-amber-300" },

  // ===== 新西兰 (10+) =====
  { id: "the-whale-rider", title: "骑鲸人", titleEn: "The Whale Rider", author: "威提·依希马埃拉", country: "新西兰", flag: "🇳🇿", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "自然", "魔幻"], year: 1987, excerpt: "毛利族女孩卡胡从一出生就被酋长祖父忽视——因为她是女孩，不是传统中的男性继承人。但古老的鲸鱼听见了她的呼唤——一部关于性别、传统与自然之灵的小说。", gradient: "from-blue-600 via-teal-500 to-white" },
  { id: "the-rainbow-warrior", title: "彩虹勇士", titleEn: "", author: "大卫·罗比", country: "新西兰", flag: "🇳🇿", continent: "oceania", era: "当代 (1950—)", genre: ["散文/随笔"], themes: ["社会", "自然", "历史"], year: 2005, excerpt: "记录了绿色和平组织旗舰'彩虹勇士号'被法国特工炸沉的真实事件。新西兰文学中关于环保、反核与主权的重要非虚构作品。", gradient: "from-green-500 via-rainbow-400 to-blue-300" },

  // ===== 太平洋岛国 (10+) =====
  { id: "tales-of-the-tikongs", title: "蒂孔的故事", titleEn: "Tales of the Tikongs", author: "埃佩利·豪奥法", country: "斐济", flag: "🇫🇯", continent: "oceania", era: "当代 (1950—)", genre: ["民间故事", "小说"], themes: ["社会", "哲学"], year: 1983, excerpt: "以幽默与讽刺写成的太平洋岛国寓言集。豪奥法以'蒂科'这座虚构的太平洋小岛为舞台，以笑声瓦解了殖民主义与'发展'的神话。", gradient: "from-blue-500 via-gold-400 to-green-300" },
  { id: "where-we-once-belonged", title: "我们曾经属于的地方", titleEn: "Where We Once Belonged", author: "西亚·菲吉尔", country: "萨摩亚", flag: "🇼🇸", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 1996, excerpt: "萨摩亚少女在传统与现代之间寻找自我的成长小说。菲吉尔以诗意的笔触呈现了太平洋女性的经验——在西方的'凝视'之外。", gradient: "from-teal-500 via-blue-400 to-purple-300" },
];
