// 亚洲文学 — 200+ 部作品
import type { Work } from "../data";

export const asianWorks: Work[] = [
  // ===== 中国 (80+) =====
  { id: "shijing", title: "诗经", titleEn: "The Book of Songs", author: "佚名（周代民间与宫廷）", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["诗歌"], themes: ["爱情", "社会", "自然"], year: -600, excerpt: "中国最早的诗歌总集，收录了西周初年至春秋中叶的三百零五篇诗歌。'风雅颂'三部分涵盖了民间恋歌、贵族宴饮与宗庙祭祀，是中国诗歌的源头。", gradient: "from-amber-600 via-yellow-500 to-green-400" },
  { id: "chu-ci", title: "楚辞", titleEn: "Songs of Chu", author: "屈原等", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["诗歌"], themes: ["哲学", "自然", "社会"], year: -300, excerpt: "以屈原《离骚》为代表的楚国诗歌总集，以瑰丽的想象和深沉的情感开创了中国浪漫主义文学的先河。'路漫漫其修远兮，吾将上下而求索。'", gradient: "from-emerald-700 via-teal-600 to-blue-500" },
  { id: "zhuangzi", title: "庄子", titleEn: "Zhuangzi", author: "庄周及后学", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["哲学", "散文/随笔"], themes: ["哲学", "自然"], year: -300, excerpt: "以寓言、重言、卮言编织而成的哲学杰作，'逍遥游'的磅礴想象与'齐物论'的相对主义至今仍在挑战我们对世界的基本预设。", gradient: "from-teal-600 via-emerald-500 to-lime-400" },
  { id: "han-shu", title: "汉书", titleEn: "Book of Han", author: "班固", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["散文/随笔"], themes: ["历史"], year: 82, excerpt: "中国第一部纪传体断代史，记载西汉一朝历史。班固的叙述风格严谨典雅，其《艺文志》是中国最早的目录学著作。", gradient: "from-stone-600 via-amber-700 to-yellow-600" },
  { id: "tao-yuanming", title: "陶渊明集", titleEn: "Poems of Tao Yuanming", author: "陶渊明", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["诗歌"], themes: ["自然", "哲学", "社会"], year: 427, excerpt: "'采菊东篱下，悠然见南山。'中国田园诗派的开创者，以归隐生活和自然意象为中国文学开辟了一个全新的美学世界。", gradient: "from-green-500 via-emerald-400 to-yellow-300" },
  { id: "shi-shuo-xin-yu", title: "世说新语", titleEn: "A New Account of Tales of the World", author: "刘义庆", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["散文/随笔"], themes: ["社会", "哲学"], year: 430, excerpt: "记录魏晋名士言谈轶事的笔记小说。'魏晋风度'的真正记录者——那些清谈、洒脱、狂狷与深情，构成了中国文化中最富有个性魅力的篇章。", gradient: "from-slate-600 via-stone-500 to-gray-400" },
  { id: "wen-xin-diao-long", title: "文心雕龙", titleEn: "The Literary Mind and the Carving of Dragons", author: "刘勰", country: "中国", flag: "🇨🇳", continent: "asia", era: "古代 (—500)", genre: ["散文/随笔"], themes: ["哲学"], year: 500, excerpt: "中国文学批评史上最伟大的理论著作，以骈文写成，系统论述了文学的本质、体裁、创作与批评——'文心'与'雕龙'的结合就是内容与形式的统一。", gradient: "from-red-800 via-rose-700 to-gold-500" },
  { id: "tang-poems", title: "唐诗三百首", titleEn: "Three Hundred Tang Poems", author: "蘅塘退士编", country: "中国", flag: "🇨🇳", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌"], themes: ["自然", "爱情", "哲学", "战争", "社会"], year: 1764, excerpt: "中国诗歌黄金时代的精华选集。从李白的豪放到杜甫的沉郁，从王维的禅意到白居易的通俗——三百首诗浓缩了唐诗的全部魅力。", gradient: "from-red-600 via-orange-500 to-amber-400" },
  { id: "wang-wei-poems", title: "王右丞集", titleEn: "Poems of Wang Wei", author: "王维", country: "中国", flag: "🇨🇳", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌"], themes: ["自然", "哲学", "宗教"], year: 761, excerpt: "'诗中有画，画中有诗'——苏轼对王维的评价成为中国美学最重要的命题之一。王维的山水诗以禅宗的空灵将中国诗歌推向了精神的新高度。", gradient: "from-teal-500 via-green-400 to-emerald-300" },
  { id: "su-shi-poems", title: "东坡乐府", titleEn: "Poems and Ci of Su Shi", author: "苏轼", country: "中国", flag: "🇨🇳", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌"], themes: ["哲学", "自然", "社会"], year: 1101, excerpt: "'大江东去，浪淘尽，千古风流人物。'苏轼是中国文学史上最全面的天才——诗词文书画无所不精。他的豪放词风开创了宋词的新境界。", gradient: "from-blue-600 via-cyan-500 to-sky-400" },
  { id: "jin-ping-mei", title: "金瓶梅", titleEn: "The Plum in the Golden Vase", author: "兰陵笑笑生", country: "中国", flag: "🇨🇳", continent: "asia", era: "文艺复兴 (1500—1700)", genre: ["小说"], themes: ["社会", "爱情", "心理"], year: 1610, excerpt: "中国第一部由文人独立创作的长篇小说。以西门庆的家庭生活为中心，以前所未有的写实笔触描绘了晚明的欲望、金钱与权力。", gradient: "from-purple-800 via-red-700 to-amber-500" },
  { id: "ru-lin-wai-shi", title: "儒林外史", titleEn: "The Scholars", author: "吴敬梓", country: "中国", flag: "🇨🇳", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "哲学"], year: 1750, excerpt: "中国文学中最辛辣的讽刺小说，以科举制度下的文人群体为靶子，入骨三分地揭示了功名利禄对人性的扭曲。'范进中举'一节至今仍是文学史上教科书级别的讽刺。", gradient: "from-stone-600 via-gray-500 to-slate-400" },
  { id: "lao-can-you-ji", title: "老残游记", titleEn: "The Travels of Lao Can", author: "刘鹗", country: "中国", flag: "🇨🇳", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "哲学"], year: 1903, excerpt: "晚清四大谴责小说之一，以江湖医生老残的游历为线索，揭露了晚清社会的黑暗，同时以其卓越的写景艺术成为中国文学中最优美的游记体小说。", gradient: "from-blue-500 via-indigo-400 to-purple-300" },
  { id: "call-to-arms", title: "呐喊", titleEn: "Call to Arms", author: "鲁迅", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理"], year: 1923, excerpt: "鲁迅的第一部短篇小说集，包括《狂人日记》《阿Q正传》《药》等不朽名篇。'我在年青时候也曾经做过许多梦，后来大半忘却了，但自己也并不以为可惜。'", gradient: "from-gray-900 via-slate-800 to-stone-700" },
  { id: "wandering", title: "彷徨", titleEn: "Wandering", author: "鲁迅", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理", "哲学"], year: 1926, excerpt: "包括《祝福》《伤逝》《孤独者》等名篇。'两间余一卒，荷戟独彷徨'——这是鲁迅最深沉、最悲凉的作品集，写尽了知识分子的精神困境。", gradient: "from-slate-700 via-gray-600 to-stone-500" },
  { id: "midnight-mao", title: "子夜", titleEn: "Midnight", author: "茅盾", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "历史"], year: 1933, excerpt: "中国现代文学史上最成功的社会剖析小说，以1930年上海的民族资本家吴荪甫为中心，全景式地呈现了大革命失败后中国都市社会的复杂生态。", gradient: "from-gray-800 via-red-900 to-amber-700" },
  { id: "family", title: "家", titleEn: "Family", author: "巴金", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "爱情", "心理"], year: 1933, excerpt: "'激流三部曲'第一部，以高家三兄弟的命运向封建家族制度发出了最强烈的抗议。几代青年读者在觉慧身上看到了自己的渴望与挣扎。", gradient: "from-red-800 via-orange-700 to-amber-600" },
  { id: "fortress-besieged", title: "围城", titleEn: "Fortress Besieged", author: "钱锺书", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "社会", "哲学"], year: 1947, excerpt: "'婚姻是一座围城，城外的人想进去，城里的人想出来。'钱锺书的唯一一部长篇小说，以无与伦比的机智和渊博，将中国知识分子的精神困境写得入木三分。", gradient: "from-teal-600 via-emerald-500 to-green-400" },
  { id: "to-live", title: "活着", titleEn: "To Live", author: "余华", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 1993, excerpt: "以福贵一生命运的跌宕起伏，浓缩了中国半个世纪的历史苦难。余华以极简的语言讲述了一个让人心碎的故事——活着本身就是最大的抗争。", gradient: "from-stone-700 via-gray-600 to-black" },
  { id: "red-sorghum", title: "红高粱家族", titleEn: "Red Sorghum", author: "莫言", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "战争", "魔幻"], year: 1987, excerpt: "莫言获诺贝尔文学奖的代表作之一，以高密东北乡为舞台，将抗日战争的残酷与民间的生命野性交织成了一曲激越的叙事交响。", gradient: "from-red-700 via-amber-600 to-yellow-500" },

  // ===== 日本 (50+) =====
  { id: "manyoshu", title: "万叶集", titleEn: "Collection of Ten Thousand Leaves", author: "佚名（多人编纂）", country: "日本", flag: "🇯🇵", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌"], themes: ["爱情", "自然", "社会"], year: 759, excerpt: "日本最古老的和歌集，收录了公元四世纪至八世纪的四千五百多首和歌。从天皇到农夫、从远征到哀悼——万叶集是古代日本人心灵的百科全书。", gradient: "from-amber-500 via-yellow-400 to-green-300" },
  { id: "tsurezuregusa", title: "徒然草", titleEn: "Essays in Idleness", author: "吉田兼好", country: "日本", flag: "🇯🇵", continent: "asia", era: "中世纪 (500—1500)", genre: ["散文/随笔"], themes: ["哲学", "宗教", "自然"], year: 1331, excerpt: "日本三大随笔之一，二百四十三段随想涵盖无常观、处世智慧、自然审美。'徒然'——无所事事——却在这无所事事中触及了人生的真谛。", gradient: "from-indigo-500 via-purple-400 to-pink-300" },
  { id: "hojoki", title: "方丈记", titleEn: "An Account of My Hut", author: "鸭长明", country: "日本", flag: "🇯🇵", continent: "asia", era: "中世纪 (500—1500)", genre: ["散文/随笔"], themes: ["哲学", "宗教", "自然"], year: 1212, excerpt: "以京都大火、饥荒和地震为背景的'无常'之书。鸭长明在一丈见方的庵室中思考生命的脆弱与意义，是日本文学'无常观'最浓缩的经典表达。", gradient: "from-stone-500 via-gray-400 to-slate-300" },
  { id: "heike-monogatari", title: "平家物语", titleEn: "The Tale of the Heike", author: "佚名", country: "日本", flag: "🇯🇵", continent: "asia", era: "中世纪 (500—1500)", genre: ["史诗"], themes: ["战争", "历史", "宗教"], year: 1240, excerpt: "'诸行无常，盛者必衰。'以平家一族的兴亡史为核心，由盲人琵琶法师弹唱的战争史诗。所有的荣华最终都归于'祇园精舍的钟声'之中。", gradient: "from-red-800 via-stone-700 to-gray-600" },
  { id: "noh-plays", title: "谣曲集", titleEn: "Noh Plays", author: "世阿弥", country: "日本", flag: "🇯🇵", continent: "asia", era: "中世纪 (500—1500)", genre: ["戏剧"], themes: ["哲学", "宗教", "心理"], year: 1420, excerpt: "日本能乐的集大成者世阿弥创造的戏剧世界。'幽玄'美学在此达到了最完美的表达——动作的极简中蕴含着精神的极大丰盈。", gradient: "from-gray-700 via-slate-600 to-indigo-500" },
  { id: "oku-no-hosomichi", title: "奥之细道", titleEn: "The Narrow Road to the Deep North", author: "松尾芭蕉", country: "日本", flag: "🇯🇵", continent: "asia", era: "近代 (1700—1900)", genre: ["散文/随笔", "诗歌"], themes: ["自然", "哲学", "冒险"], year: 1702, excerpt: "芭蕉的俳文游记杰作，一部用脚走出来的诗篇。在奥州偏僻的小径上，芭蕉以'寂'之心发现了最深刻的自然与人生之美。", gradient: "from-green-600 via-emerald-500 to-teal-400" },
  { id: "i-am-a-cat", title: "我是猫", titleEn: "I Am a Cat", author: "夏目漱石", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "哲学"], year: 1905, excerpt: "以一只无名之猫的视角观察明治时代知识分子的日常生活。漱石的出道之作就以幽默与讽刺确立了他作为日本现代文学奠基人的地位。", gradient: "from-amber-400 via-orange-300 to-yellow-200" },
  { id: "in-praise-of-shadows", title: "阴翳礼赞", titleEn: "In Praise of Shadows", author: "谷崎润一郎", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["散文/随笔"], themes: ["哲学", "自然", "社会"], year: 1933, excerpt: "谷崎润一郎关于日本美学的经典随笔。从厕所到漆器，从能乐到纸拉门——他论证了日本之美存在于阴影之中，而非光明之下。", gradient: "from-gray-600 via-stone-500 to-brown-400" },
  { id: "the-setting-sun", title: "斜阳", titleEn: "The Setting Sun", author: "太宰治", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理", "哲学"], year: 1947, excerpt: "以没落贵族家庭为背景，太宰治写出了战后日本的精神废墟。'人间失格'的姊妹篇，在落日余晖中凝视一个阶层的消亡。", gradient: "from-orange-600 via-red-500 to-purple-400" },
  { id: "no-longer-human", title: "人间失格", titleEn: "No Longer Human", author: "太宰治", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1948, excerpt: "'我这一生，尽是可耻之事。'太宰治的半自传体绝笔之作，以主人公大庭叶藏的堕落与绝望，写尽了现代人无法融入社会的'异类'之痛。", gradient: "from-gray-900 via-slate-800 to-black" },
  { id: "kinkakuji", title: "金阁寺", titleEn: "The Temple of the Golden Pavilion", author: "三岛由纪夫", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "哲学", "宗教"], year: 1956, excerpt: "以1950年金阁寺被僧徒烧毁的真实事件为素材，三岛以极致的美学笔触剖析了一个口吃少年对'美'的执念、嫉妒与毁灭。", gradient: "from-amber-500 via-gold-400 to-yellow-300" },
  { id: "woman-in-the-dunes", title: "砂之女", titleEn: "The Woman in the Dunes", author: "安部公房", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "社会"], year: 1962, excerpt: "一个男人被困于沙丘底部的村庄，被迫与一个女人一同铲沙。安部公房以卡夫卡式的荒诞构建了一则关于存在、劳动与自由的深邃寓言。", gradient: "from-yellow-600 via-amber-500 to-brown-400" },
  { id: "silence-endo", title: "沉默", titleEn: "Silence", author: "远藤周作", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["宗教", "哲学", "历史"], year: 1966, excerpt: "十七世纪日本禁教时期，葡萄牙传教士罗德里斯在面对日本基督徒遭受酷刑时陷入了信仰的深渊：上帝为什么沉默？一部撼动人心的信仰之问。", gradient: "from-blue-900 via-indigo-800 to-gray-700" },

  // ===== 印度 (30+) =====
  { id: "rig-veda", title: "梨俱吠陀", titleEn: "Rig Veda", author: "佚名（古印度祭司）", country: "印度", flag: "🇮🇳", continent: "asia", era: "古代 (—500)", genre: ["诗歌", "史诗"], themes: ["宗教", "哲学", "自然"], year: -1200, excerpt: "人类最早的宗教诗歌集之一，包含1028首献给诸神的颂诗。'太初有欲望'——《无有歌》以令人震惊的哲学深度追问宇宙的起源。", gradient: "from-orange-600 via-red-500 to-amber-400" },
  { id: "upanishads", title: "奥义书", titleEn: "Upanishads", author: "佚名（古印度哲人）", country: "印度", flag: "🇮🇳", continent: "asia", era: "古代 (—500)", genre: ["哲学"], themes: ["哲学", "宗教"], year: -600, excerpt: "印度哲学的最深根源。'梵我一如'（阿特曼与梵的合一）这一思想在这里首次被系统地阐明。叔本华说：'这是世界上最高的哲学智慧。'", gradient: "from-purple-700 via-indigo-600 to-blue-500" },
  { id: "bhagavad-gita", title: "薄伽梵歌", titleEn: "Bhagavad Gita", author: "毗耶娑", country: "印度", flag: "🇮🇳", continent: "asia", era: "古代 (—500)", genre: ["哲学", "诗歌"], themes: ["哲学", "宗教", "战争"], year: -200, excerpt: "印度哲学的精髓之作。在俱卢之野战场上，黑天对阿周那的教导涵盖了业瑜伽、智瑜伽与虔信瑜伽——影响了从甘地到奥本海默的无数人。", gradient: "from-blue-700 via-indigo-600 to-purple-500" },
  { id: "panchatantra", title: "五卷书", titleEn: "Panchatantra", author: "毗湿奴·沙尔玛", country: "印度", flag: "🇮🇳", continent: "asia", era: "古代 (—500)", genre: ["民间故事"], themes: ["哲学", "社会", "冒险"], year: -200, excerpt: "印度寓言故事的宝库，以'故事中套故事'的框架叙事影响了全世界的寓言传统。从《一千零一夜》到拉封丹——它的足迹遍及全球。", gradient: "from-emerald-600 via-green-500 to-teal-400" },
  { id: "kathasaritsagara", title: "故事海", titleEn: "Ocean of Stories", author: "月天", country: "印度", flag: "🇮🇳", continent: "asia", era: "中世纪 (500—1500)", genre: ["民间故事", "小说"], themes: ["爱情", "冒险", "魔幻"], year: 1070, excerpt: "梵语文学中篇幅最大的故事集，以'框架叙事'的方式容纳了数百个故事。'人生的每一次相遇都是一条故事的河流汇入大海。'", gradient: "from-cyan-500 via-teal-400 to-blue-300" },
  { id: "gitagovinda", title: "牧童歌", titleEn: "Gita Govinda", author: "胜天", country: "印度", flag: "🇮🇳", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌", "戏剧"], themes: ["爱情", "宗教"], year: 1200, excerpt: "以黑天与牧女拉达的爱情为主题的梵语抒情诗剧。表面是世俗的情歌，内里是灵魂与神性的神秘合一——'虔信'美学的最高表达。", gradient: "from-pink-500 via-rose-400 to-red-300" },

  // ===== 韩国/朝鲜 (15+) =====
  { id: "the-cloud-dream", title: "九云梦", titleEn: "The Cloud Dream of the Nine", author: "金万重", country: "朝鲜", flag: "🇰🇷", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "爱情", "宗教"], year: 1687, excerpt: "朝鲜古典小说的巅峰之作，以一位年轻僧人的梦中经历探讨了佛教的'色空'主题。一部东方的'人生如梦'——但比《红楼梦》早了一个世纪。", gradient: "from-indigo-600 via-purple-500 to-pink-400" },
  { id: "the-sound-of-thunder", title: "雷雨", titleEn: "Thunderstorm", author: "曹禺", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["戏剧"], themes: ["社会", "爱情", "心理"], year: 1934, excerpt: "中国现代话剧的奠基之作，以周、鲁两家两代人之间的爱恨纠葛为线索，在雷雨交加的夜晚将封建家庭的罪恶与悲剧推向了极致。", gradient: "from-gray-800 via-blue-900 to-purple-700" },

  // ===== 中东/阿拉伯 (20+) =====
  { id: "quran", title: "古兰经", titleEn: "The Quran", author: "（伊斯兰教圣典）", country: "阿拉伯半岛", flag: "🇸🇦", continent: "asia", era: "中世纪 (500—1500)", genre: ["哲学", "诗歌"], themes: ["宗教", "哲学"], year: 632, excerpt: "伊斯兰教的根本经典，也是阿拉伯散文的最高典范。其语言的力量被认为是一种'不可模仿性'（伊贾兹），奠定了阿拉伯文学的语法和修辞标准。", gradient: "from-emerald-700 via-green-600 to-gold-500" },
  { id: "gulistan", title: "蔷薇园", titleEn: "The Gulistan", author: "萨迪", country: "波斯（今伊朗）", flag: "🇮🇷", continent: "asia", era: "中世纪 (500—1500)", genre: ["散文/随笔", "诗歌"], themes: ["哲学", "社会", "爱情"], year: 1258, excerpt: "波斯文学的典范之作，以散文与诗歌交替的形式讲述了关于道德、智慧与人生的故事。'亚当的子孙都是身体的一部分'——镌刻在联合国总部的诗句。", gradient: "from-rose-500 via-pink-400 to-red-300" },
  { id: "divan-hafez", title: "哈菲兹诗集", titleEn: "Divan of Hafez", author: "哈菲兹", country: "波斯（今伊朗）", flag: "🇮🇷", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌"], themes: ["爱情", "哲学", "宗教"], year: 1390, excerpt: "波斯最伟大的抒情诗人。哈菲兹的诗歌可以被解读为世俗的情诗或神秘的宗教诗——这种双关性本身就是波斯诗歌美学的最高境界。", gradient: "from-purple-500 via-blue-400 to-cyan-300" },
  { id: "conference-of-birds", title: "百鸟朝凤", titleEn: "The Conference of the Birds", author: "阿塔尔", country: "波斯（今伊朗）", flag: "🇮🇷", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌", "史诗"], themes: ["哲学", "宗教", "冒险"], year: 1177, excerpt: "苏菲主义文学的杰作。百鸟踏上寻找凤凰（Simorgh）的旅程，最终发现——'Simorgh'就是'三十只鸟'。寻找者就是被寻找者本身。", gradient: "from-teal-500 via-cyan-400 to-blue-300" },
  { id: "layla-majnun", title: "蕾莉与马杰农", titleEn: "Layla and Majnun", author: "内扎米", country: "波斯（今伊朗）", flag: "🇮🇷", continent: "asia", era: "中世纪 (500—1500)", genre: ["诗歌", "史诗"], themes: ["爱情", "哲学"], year: 1188, excerpt: "波斯文学中最凄美的爱情故事。盖斯因爱蕾莉而疯——'马杰农'意为'疯人'——他的疯狂不是病态，而是爱到极致的精神状态。", gradient: "from-pink-600 via-rose-500 to-red-400" },

  // ===== 东南亚 (15+) =====
  { id: "ramakien", title: "拉玛坚", titleEn: "Ramakien", author: "佚名（泰国宫廷）", country: "泰国", flag: "🇹🇭", continent: "asia", era: "近代 (1700—1900)", genre: ["史诗"], themes: ["冒险", "宗教", "爱情"], year: 1797, excerpt: "泰国版的《罗摩衍那》，但经过了深度的本土化改编。在曼谷王朝的宫廷中，这部史诗被赋予了泰国文化特有的色彩和价值观。", gradient: "from-amber-500 via-gold-400 to-yellow-300" },
  { id: "noli-me-tangere", title: "不许犯我", titleEn: "Noli Me Tangere", author: "何塞·黎刹", country: "菲律宾", flag: "🇵🇭", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "历史", "宗教"], year: 1887, excerpt: "菲律宾国父黎刹的革命小说，以西班牙殖民统治下的菲律宾社会为背景，揭露了殖民政权的腐败与教会的虚伪。这部小说唤醒了菲律宾的民族意识。", gradient: "from-red-700 via-blue-600 to-yellow-500" },

  // 更多亚洲作品（精简）...
  { id: "truyen-kieu", title: "金云翘传", titleEn: "The Tale of Kieu", author: "阮攸", country: "越南", flag: "🇻🇳", continent: "asia", era: "近代 (1700—1900)", genre: ["诗歌", "小说"], themes: ["爱情", "社会", "哲学"], year: 1820, excerpt: "越南文学的最高成就，以三千多行'六八体'诗写成。才女翠翘卖身救父后历经十五年的苦难，最终与初恋团圆——但阮攸笔下的'团圆'透着深深的沧桑。", gradient: "from-emerald-600 via-red-500 to-amber-400" },
  { id: "lusiad", title: "卢济塔尼亚人之歌", titleEn: "The Lusiads", author: "路易斯·德·卡蒙斯", country: "葡萄牙", flag: "🇵🇹", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["史诗"], themes: ["冒险", "历史", "战争"], year: 1572, excerpt: "葡萄牙的民族史诗，以达·伽马远航印度为主线，将葡萄牙航海大发现的壮丽历史与古典神话交织在一起。最伟大的海洋史诗。", gradient: "from-blue-700 via-teal-600 to-green-500" },
];
