// 欧洲文学 — 280+ 部作品
import type { Work } from "../data";

export const europeanWorks: Work[] = [
  // ===== 古希腊/罗马 (30+) =====
  { id: "oresteia", title: "俄瑞斯忒亚", titleEn: "The Oresteia", author: "埃斯库罗斯", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["戏剧"], themes: ["哲学", "社会", "历史"], year: -458, excerpt: "西方戏剧史上唯一保存完整的古希腊三联剧。从阿伽门农的归来、祭杀到俄瑞斯忒斯的审判——实现了从复仇正义到城邦法治的文明跃迁。", gradient: "from-red-900 via-stone-800 to-amber-700" },
  { id: "antigone", title: "安提戈涅", titleEn: "Antigone", author: "索福克勒斯", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["戏剧"], themes: ["哲学", "社会"], year: -441, excerpt: "安提戈涅违抗国王禁令埋葬兄长——'自然法'与'人定法'的永恒冲突。从黑格尔到朱迪斯·巴特勒，哲学从未停止与安提戈涅对话。", gradient: "from-stone-700 via-purple-800 to-rose-600" },
  { id: "the-bacchae", title: "酒神的伴侣", titleEn: "The Bacchae", author: "欧里庇得斯", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["戏剧"], themes: ["宗教", "心理", "哲学"], year: -405, excerpt: "欧里庇得斯的遗作。酒神狄俄尼索斯的到来撕裂了忒拜城的理性秩序——理性主义的局限和原始欲望的力量在此被推向极端。", gradient: "from-purple-700 via-fuchsia-600 to-rose-500" },
  { id: "lysistrata", title: "吕西斯特拉忒", titleEn: "Lysistrata", author: "阿里斯托芬", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["戏剧"], themes: ["战争", "社会", "爱情"], year: -411, excerpt: "雅典妇女以'性罢工'迫使男人结束战争——西方最早的关于性别、战争与和平的喜剧。两千多年后，反战喜剧的典范依然是它。", gradient: "from-amber-400 via-yellow-300 to-pink-300" },
  { id: "the-symposium", title: "会饮篇", titleEn: "The Symposium", author: "柏拉图", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["哲学", "散文/随笔"], themes: ["爱情", "哲学"], year: -385, excerpt: "一场关于爱（Eros）的酒宴对话。从肉身之美到理念之美——柏拉图式的爱不是对性的否定，而是一架从可感世界通向可知世界的'美的阶梯'。", gradient: "from-blue-600 via-indigo-500 to-purple-400" },
  { id: "the-histories", title: "历史", titleEn: "The Histories", author: "希罗多德", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["散文/随笔"], themes: ["历史", "战争"], year: -425, excerpt: "西方第一部历史著作，记录了希波战争以及他所游历的整个已知世界。希罗多德被称为'历史之父'——也被称为'谎言之父'——因为他在历史叙事中同时是严谨的史家和迷人的说书人。", gradient: "from-stone-500 via-amber-400 to-gold-300" },
  { id: "peloponnesian-war", title: "伯罗奔尼撒战争史", titleEn: "History of the Peloponnesian War", author: "修昔底德", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["散文/随笔"], themes: ["战争", "历史", "哲学"], year: -400, excerpt: "第一部严格意义上的'科学史学'著作。修昔底德以冷静得近乎冷酷的笔调记录了雅典与斯巴达之间的毁灭性战争——'强者做他们能做的，弱者受他们必须受的。'", gradient: "from-gray-700 via-slate-600 to-stone-500" },
  { id: "lives", title: "希腊罗马名人传", titleEn: "Parallel Lives", author: "普鲁塔克", country: "古希腊", flag: "🇬🇷", continent: "europe", era: "古代 (—500)", genre: ["散文/随笔"], themes: ["历史", "哲学"], year: 100, excerpt: "将希腊与罗马的伟人两两对照，普鲁塔克开创了一种独特的传记体裁。莎士比亚的罗马剧几乎全部取材于此书——事实上，普鲁塔克比任何一位历史学家都更深刻地塑造了西方对古典世界的想象。", gradient: "from-amber-600 via-marble-400 to-gold-300" },
  { id: "confessions-augustine", title: "忏悔录", titleEn: "Confessions", author: "奥古斯丁", country: "罗马帝国（北非）", flag: "🇩🇿", continent: "europe", era: "古代 (—500)", genre: ["散文/随笔", "哲学"], themes: ["宗教", "哲学", "心理"], year: 400, excerpt: "西方第一部真正的自传。奥古斯丁对自己的少年偷梨事件进行了深度的神学与心理学分析——'人心是为祢而造的，除非安息于祢，否则永无安宁。'", gradient: "from-purple-800 via-indigo-700 to-blue-600" },

  // ===== 中世纪/文艺复兴 (40+) =====
  { id: "beowulf", title: "贝奥武夫", titleEn: "Beowulf", author: "佚名", country: "英格兰", flag: "🏴", continent: "europe", era: "中世纪 (500—1500)", genre: ["史诗"], themes: ["战争", "冒险", "魔幻"], year: 800, excerpt: "古英语文学的顶峰，北欧英雄传奇的典范。贝奥武夫与怪物格兰戴尔、格兰戴尔之母及火龙的三场战斗，是英雄主义精神的最古老回响。", gradient: "from-stone-700 via-gray-600 to-slate-500" },
  { id: "song-of-roland", title: "罗兰之歌", titleEn: "The Song of Roland", author: "佚名", country: "法兰西", flag: "🇫🇷", continent: "europe", era: "中世纪 (500—1500)", genre: ["史诗"], themes: ["战争", "宗教", "历史"], year: 1100, excerpt: "法国最古老的英雄史诗，以查理大帝的部将罗兰在龙塞斯瓦列斯山口壮烈战死的故事为核心。'罗兰吹响了号角'——忠诚与荣誉的史诗绝唱。", gradient: "from-blue-800 via-red-700 to-gold-500" },
  { id: "nibelungenlied", title: "尼伯龙根之歌", titleEn: "The Song of the Nibelungs", author: "佚名", country: "德意志", flag: "🇩🇪", continent: "europe", era: "中世纪 (500—1500)", genre: ["史诗"], themes: ["战争", "爱情", "历史"], year: 1200, excerpt: "德意志的中古英雄史诗，以齐格弗里德之死和克里姆希尔德的复仇为主线。瓦格纳的《指环》四联剧即取材于此——北欧神话与日耳曼传奇的永恒回声。", gradient: "from-gray-800 via-red-800 to-black" },
  { id: "sir-gawain", title: "高文爵士与绿骑士", titleEn: "Sir Gawain and the Green Knight", author: "佚名（同《珍珠》诗人）", country: "英格兰", flag: "🏴", continent: "europe", era: "中世纪 (500—1500)", genre: ["诗歌", "史诗"], themes: ["冒险", "哲学", "魔幻"], year: 1400, excerpt: "中古英语韵文罗曼史的杰作。亚瑟王的侄子高文接受绿骑士的砍头游戏——这是一首关于骑士精神、诱惑与人性脆弱的精美诗篇。", gradient: "from-green-700 via-emerald-600 to-teal-500" },
  { id: "canterbury-tales", title: "坎特伯雷故事集", titleEn: "The Canterbury Tales", author: "杰弗里·乔叟", country: "英格兰", flag: "🏴", continent: "europe", era: "中世纪 (500—1500)", genre: ["小说", "诗歌"], themes: ["社会", "爱情", "宗教"], year: 1400, excerpt: "一群前往坎特伯雷的朝圣者各讲故事——磨坊主、巴斯妇、学者、骑士……每一个故事都带着讲述者的阶级、性格与欲望。乔叟凭此成为'英语诗歌之父'。", gradient: "from-amber-500 via-red-400 to-brown-300" },
  { id: "le-morte-darthur", title: "亚瑟王之死", titleEn: "Le Morte d'Arthur", author: "托马斯·马洛礼", country: "英格兰", flag: "🏴", continent: "europe", era: "中世纪 (500—1500)", genre: ["史诗", "民间故事"], themes: ["冒险", "爱情", "宗教"], year: 1485, excerpt: "亚瑟王传奇的集大成之作。从石中剑到圆桌骑士、从圣杯到最后的战役——马洛礼将几个世纪的亚瑟王传说熔铸为一部连贯的英语散文史诗。", gradient: "from-blue-700 via-purple-600 to-gold-400" },
  { id: "gargantua", title: "巨人传", titleEn: "Gargantua and Pantagruel", author: "弗朗索瓦·拉伯雷", country: "法国", flag: "🇫🇷", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["小说"], themes: ["哲学", "社会", "冒险"], year: 1534, excerpt: "以巨人父子狂欢式的冒险为载体，拉伯雷以颠覆性的笑声瓦解了中世纪经院哲学的权威。巴赫金说这部书是'民间笑文化的百科全书'。", gradient: "from-emerald-500 via-green-400 to-yellow-300" },
  { id: "essais-montaigne", title: "随笔集", titleEn: "Essays", author: "米歇尔·德·蒙田", country: "法国", flag: "🇫🇷", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["散文/随笔"], themes: ["哲学", "心理", "社会"], year: 1580, excerpt: "'我知道什么？'（Que sais-je?）——蒙田以这句座右铭发明了'随笔'这一体裁。他在自我解剖中发现了普遍的人性，因而成为所有随笔作家的祖师爷。", gradient: "from-amber-600 via-stone-400 to-brown-300" },
  { id: "doctor-faustus", title: "浮士德博士的悲剧", titleEn: "Doctor Faustus", author: "克里斯托弗·马洛", country: "英格兰", flag: "🏴", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["戏剧"], themes: ["哲学", "宗教", "心理"], year: 1592, excerpt: "'这就是那张引起千帆竞发的脸庞吗？'马洛的无韵诗与浮士德灵魂交易的悲剧——知识、权力与永罚之间永恒的张力。", gradient: "from-red-900 via-purple-800 to-black" },

  // ===== 英国 18-20世纪 (40+) =====
  { id: "robinson-crusoe", title: "鲁滨逊漂流记", titleEn: "Robinson Crusoe", author: "丹尼尔·笛福", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["冒险", "哲学", "自然"], year: 1719, excerpt: "被认为是英语第一部真正意义上的小说。一个人在荒岛上二十八年——笛福以'纪实'笔法书写了一个关于孤独、劳动与信仰的现代寓言。", gradient: "from-amber-600 via-sand-400 to-teal-300" },
  { id: "gullivers-travels", title: "格列佛游记", titleEn: "Gulliver's Travels", author: "乔纳森·斯威夫特", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "冒险", "哲学"], year: 1726, excerpt: "小人国、大人国、飞岛国、智马国——斯威夫特以'童书'的外壳包装了人类文明史上最激进的讽刺。当你长大了再读，你会发笑，然后不寒而栗。", gradient: "from-teal-500 via-blue-400 to-purple-300" },
  { id: "tom-jones", title: "汤姆·琼斯", titleEn: "Tom Jones", author: "亨利·菲尔丁", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "社会", "冒险"], year: 1749, excerpt: "英语文学中最伟大的'成长小说'之一。弃儿汤姆·琼斯在十八世纪英国社会中的荒唐冒险与成长，菲尔丁以机智的叙事者身份直接对读者说话——元小说的雏形。", gradient: "from-green-500 via-yellow-400 to-red-300" },
  { id: "tristram-shandy", title: "项狄传", titleEn: "Tristram Shandy", author: "劳伦斯·斯特恩", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "心理"], year: 1760, excerpt: "比后现代主义早了两百年。全书的叙事不断被偏离、打断、延宕——一页可以是全黑的，一页可以是一段曲线。'小说'这个形式的边界在此被彻底打开。", gradient: "from-purple-500 via-indigo-400 to-gray-300" },
  { id: "emma", title: "爱玛", titleEn: "Emma", author: "简·奥斯汀", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "社会", "心理"], year: 1815, excerpt: "一个自以为能操控他人爱情的女主人公最终发现——自己才是被蒙蔽的那个人。'自由间接引语'的技术在这里达到了完美的境界。", gradient: "from-rose-400 via-pink-300 to-purple-200" },
  { id: "jane-eyre", title: "简·爱", titleEn: "Jane Eyre", author: "夏洛蒂·勃朗特", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "社会", "心理"], year: 1847, excerpt: "'读者，我嫁给了他。'一个瘦小的家庭女教师拥有不逊于任何人的灵魂——夏洛蒂以第一人称的自传体写出了维多利亚时代女性的独立宣言。", gradient: "from-purple-600 via-gray-500 to-rose-400" },
  { id: "vanity-fair", title: "名利场", titleEn: "Vanity Fair", author: "威廉·萨克雷", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "心理"], year: 1848, excerpt: "'一部没有英雄的小说'——萨克雷如此宣称。蓓基·夏泼是文学史上最迷人的'恶女'之一：你无法赞同她的行为，但你也无法移开你的目光。", gradient: "from-amber-400 via-gold-300 to-yellow-200" },
  { id: "bleak-house", title: "荒凉山庄", titleEn: "Bleak House", author: "查尔斯·狄更斯", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "历史"], year: 1853, excerpt: "以一场永无尽头的法律诉讼（詹狄士诉詹狄士案）为引子，狄更斯将叙事者对维多利亚社会的全景扫描与女主人公以斯帖的第一人称视角交替呈现——叙事结构的精巧令人叹为观止。", gradient: "from-gray-800 via-fog-400 to-slate-300" },
  { id: "the-mill-on-the-floss", title: "弗洛斯河上的磨坊", titleEn: "The Mill on the Floss", author: "乔治·艾略特", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "社会", "心理"], year: 1860, excerpt: "玛吉·塔利弗——一个充满激情的聪慧女子在维多利亚时代的压抑环境中挣扎。兄妹关系的最终和解是英语文学中最令人心碎的场景之一。", gradient: "from-teal-600 via-green-500 to-emerald-400" },
  { id: "tess-of-the-durbervilles", title: "德伯家的苔丝", titleEn: "Tess of the d'Urbervilles", author: "托马斯·哈代", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "社会", "自然"], year: 1891, excerpt: "'一个纯洁女人的真实写照'——哈代如此为苔丝辩护。在维多利亚道德的审判下，一个乡村女子的命运被他以悲剧性的笔触书写成了对宇宙公正的质问。", gradient: "from-green-700 via-brown-500 to-rose-400" },
  { id: "heart-of-darkness", title: "黑暗的心", titleEn: "Heart of Darkness", author: "约瑟夫·康拉德", country: "英国（波兰裔）", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1899, excerpt: "沿着刚果河溯流而上就是溯入人心的黑暗。库尔茨的临终遗言——'恐怖！恐怖！'——至今仍在追问着殖民、权力与人性的边界。", gradient: "from-green-900 via-black to-gray-700" },
  { id: "sons-and-lovers", title: "儿子与情人", titleEn: "Sons and Lovers", author: "D.H. 劳伦斯", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "心理", "社会"], year: 1913, excerpt: "以矿工家庭的母子关系为切入点，劳伦斯以前所未有的坦率探测了性、情感与工业文明之间的黑暗地带。弗洛伊德的'俄狄浦斯情结'在此获得了血肉之躯。", gradient: "from-coal-800 via-amber-600 to-red-500" },
  { id: "a-portrait-of-the-artist", title: "一个青年艺术家的画像", titleEn: "A Portrait of the Artist as a Young Man", author: "詹姆斯·乔伊斯", country: "爱尔兰", flag: "🇮🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "宗教"], year: 1916, excerpt: "斯蒂芬·迪达勒斯在都柏林的精神觉醒——从宗教禁锢到艺术自由的旅程。乔伊斯以意识流追踪了一个艺术家灵魂的孕育过程。", gradient: "from-green-600 via-white-300 to-orange-400" },
  { id: "mrs-dalloway", title: "达洛维夫人", titleEn: "Mrs Dalloway", author: "弗吉尼亚·伍尔夫", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1925, excerpt: "'达洛维夫人说她要自己去买花。'六月的一天，一个派对，两个人的意识之流——克拉丽莎·达洛维与赛普蒂默斯·史密斯在同一片伦敦天空下平行展开的精神旅程。", gradient: "from-rose-300 via-lavender-200 to-purple-200" },
  { id: "to-the-lighthouse", title: "到灯塔去", titleEn: "To the Lighthouse", author: "弗吉尼亚·伍尔夫", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "自然"], year: 1927, excerpt: "'一个人的生命中有多少个瞬间，能像拉姆齐夫人吩咐仆人把烤肉端进餐厅的瞬间那样，可以被凝固下来成为永恒？'伍尔夫对时间、艺术与记忆的终极沉思。", gradient: "from-blue-300 via-teal-200 to-white" },
  { id: "brave-new-world", title: "美丽新世界", titleEn: "Brave New World", author: "奥尔德斯·赫胥黎", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["哲学", "社会"], year: 1932, excerpt: "'人人属于每一个人。'赫胥黎的'快乐'反乌托邦——不再需要暴力来奴役人，只要用基因工程、精神麻醉剂和消费主义让他们'自愿'地热爱自己的奴役。", gradient: "from-gray-600 via-silver-400 to-blue-300" },
  { id: "animal-farm", title: "动物农场", titleEn: "Animal Farm", author: "乔治·奥威尔", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说", "民间故事"], themes: ["社会", "哲学"], year: 1945, excerpt: "'所有动物一律平等，但有些动物比其他动物更加平等。'一部以农场动物'革命'为幌子的寓言——奥威尔用最简洁的故事写出了关于权力最深刻的警世之言。", gradient: "from-red-700 via-brown-500 to-green-400" },
  { id: "lord-of-the-flies", title: "蝇王", titleEn: "Lord of the Flies", author: "威廉·戈尔丁", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1954, excerpt: "一群流落荒岛的英国学童从文明倒退回野蛮。戈尔丁说：'人制造恶就像蜜蜂制造蜂蜜。'一部关于人性之暗的不朽寓言。", gradient: "from-green-700 via-jungle-500 to-black" },
  { id: "atonement", title: "赎罪", titleEn: "Atonement", author: "伊恩·麦克尤恩", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "战争", "心理"], year: 2001, excerpt: "一个十三岁女孩的错误指控毁掉了两个人的一生。麦克尤恩以多层叙事追问了一个终极问题——小说能成为对现实中所犯之罪的'赎罪'吗？", gradient: "from-green-500 via-blue-400 to-rose-300" },

  // ===== 法国 (30+) =====
  { id: "candide", title: "老实人", titleEn: "Candide", author: "伏尔泰", country: "法国", flag: "🇫🇷", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "社会", "冒险"], year: 1759, excerpt: "'我们生活在所有可能世界中最好的那个。'伏尔泰以闪电般的讽刺速度将莱布尼茨的乐观主义哲学撕得粉碎。'应该耕种我们的花园'——启蒙运动最清醒的结语。", gradient: "from-blue-500 via-yellow-300 to-green-400" },
  { id: "the-red-and-the-black", title: "红与黑", titleEn: "The Red and the Black", author: "司汤达", country: "法国", flag: "🇫🇷", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["心理", "社会", "爱情"], year: 1830, excerpt: "'一部1830年纪事'——副标题如此宣告。于连·索雷尔——法国文学中最野心勃勃也最令人心碎的外省青年——'红'是军服，'黑'是教袍，而他两者都不是。", gradient: "from-red-700 via-black to-gray-600" },
  { id: "pere-goriot", title: "高老头", titleEn: "Le Père Goriot", author: "奥诺雷·德·巴尔扎克", country: "法国", flag: "🇫🇷", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "爱情", "心理"], year: 1835, excerpt: "巴尔扎克《人间喜剧》的核心之作。拉斯蒂涅在拉雪兹神父公墓山顶俯瞰巴黎——'现在，是咱俩较量的时候了！'野心家的觉醒与老父亲的牺牲构成双重悲剧。", gradient: "from-gray-700 via-stone-500 to-amber-400" },
  { id: "the-three-musketeers", title: "三个火枪手", titleEn: "The Three Musketeers", author: "大仲马", country: "法国", flag: "🇫🇷", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["冒险", "爱情", "历史"], year: 1844, excerpt: "'人人为我，我为人人！'达达尼昂与阿多斯、波尔多斯、阿拉米斯——四个性格迥异的火枪手在不计其数的阴谋与决斗中书写了最脍炙人口的冒险传奇。", gradient: "from-blue-600 via-red-500 to-gold-400" },
  { id: "the-count-of-monte-cristo", title: "基督山伯爵", titleEn: "The Count of Monte Cristo", author: "大仲马", country: "法国", flag: "🇫🇷", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["冒险", "心理", "社会"], year: 1846, excerpt: "'等待与希望。'爱德蒙·唐泰斯被诬陷入狱十四年，越狱后化身基督山伯爵——一场精心策划的复仇。但复仇的尽头是什么？", gradient: "from-blue-800 via-gold-600 to-black" },
  { id: "germinal", title: "萌芽", titleEn: "Germinal", author: "埃米尔·左拉", country: "法国", flag: "🇫🇷", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "历史"], year: 1885, excerpt: "左拉《卢贡-马卡尔家族》系列的第十三部——可能是世界文学中最具震撼力的矿井叙事。矿工在黑暗中挖掘，而'萌芽'在土壤下生长——革命的力量在地下孕育。", gradient: "from-black via-gray-800 to-red-600" },
  { id: "the-immoralist", title: "背德者", titleEn: "The Immoralist", author: "安德烈·纪德", country: "法国", flag: "🇫🇷", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学"], year: 1902, excerpt: "一场大病之后，学者米歇尔抛弃了一切道德规范，追寻感官与存在的'真实'。纪德以第一人称让读者无法简单审判——我们每个人都潜藏着一个'背德者'。", gradient: "from-amber-400 via-sand-300 to-gray-200" },
  { id: "the-little-prince", title: "小王子", titleEn: "The Little Prince", author: "安托万·德·圣-埃克苏佩里", country: "法国", flag: "🇫🇷", continent: "europe", era: "现代 (1900—1950)", genre: ["民间故事", "小说"], themes: ["哲学", "爱情", "自然"], year: 1943, excerpt: "'只有用心才能看清——本质的东西是眼睛看不见的。'一本伪装成童书的哲学杰作。狐狸、玫瑰、小王子——所有这些都在提醒每个'长大'了的人：'所有的大人最初都是孩子。'", gradient: "from-amber-300 via-gold-200 to-rose-200" },
  { id: "the-second-sex", title: "第二性", titleEn: "The Second Sex", author: "西蒙娜·德·波伏瓦", country: "法国", flag: "🇫🇷", continent: "europe", era: "当代 (1950—)", genre: ["哲学", "散文/随笔"], themes: ["社会", "哲学", "心理"], year: 1949, excerpt: "'女人不是天生的，而是后天形成的。'这句颠覆性宣言开启了第二波女性主义。波伏瓦以存在主义哲学为武器，解构了几千年来对女性的建构。", gradient: "from-purple-600 via-rose-500 to-pink-400" },

  // ===== 俄国/苏联 (30+) =====
  { id: "eugene-onegin", title: "叶甫盖尼·奥涅金", titleEn: "Eugene Onegin", author: "亚历山大·普希金", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["诗歌", "小说"], themes: ["爱情", "社会", "心理"], year: 1833, excerpt: "'俄国文学之父'普希金的'诗体小说'。奥涅金——俄国文学中第一个'多余的人'——因拒绝塔季扬娜的爱情而在决斗中杀死好友连斯基，永远无法在世界上找到自己的位置。", gradient: "from-blue-700 via-white-300 to-red-500" },
  { id: "a-hero-of-our-time", title: "当代英雄", titleEn: "A Hero of Our Time", author: "米哈伊尔·莱蒙托夫", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["心理", "社会", "冒险"], year: 1840, excerpt: "毕巧林——'多余的人'谱系中最冷酷也最迷人的人物。莱蒙托夫以多重叙事视角构建了一个你在厌恶的同时又无法不怜悯的'当代英雄'。", gradient: "from-gray-700 via-caucasus-brown to-stone-500" },
  { id: "dead-souls", title: "死魂灵", titleEn: "Dead Souls", author: "尼古莱·果戈理", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "心理"], year: 1842, excerpt: "乞乞科夫在俄罗斯大地上收购'死魂灵'——那些已经去世但尚未注销户籍的农奴。果戈理以'笑中的泪'创造了俄国文学最奇异也是最深刻的讽刺。", gradient: "from-gray-600 via-fog-300 to-brown-400" },
  { id: "fathers-and-sons", title: "父与子", titleEn: "Fathers and Sons", author: "伊万·屠格涅夫", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "哲学", "爱情"], year: 1862, excerpt: "巴扎罗夫——'虚无主义者'的原型。屠格涅夫以罕见的平衡感呈现了两代人之间的意识形态冲突——没有简单判胜，唯有真诚的理解与忧伤。", gradient: "from-green-600 via-brown-400 to-amber-300" },
  { id: "the-idiot", title: "白痴", titleEn: "The Idiot", author: "费奥多尔·陀思妥耶夫斯基", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "心理", "宗教"], year: 1869, excerpt: "梅什金公爵——一个'完全美好的人'——在彼得堡的上流社会中，他的善良不是被赞美而是被利用、最终被摧毁。陀思妥耶夫斯基以一部小说追问：善良在这个世界上可能吗？", gradient: "from-white via-gold-100 to-gray-300" },
  { id: "demons", title: "群魔", titleEn: "Demons", author: "费奥多尔·陀思妥耶夫斯基", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "社会", "心理"], year: 1872, excerpt: "以真实的政治谋杀案为素材，陀思妥耶夫斯基以冷酷的笔触解剖了虚无主义的逻辑终点——当上帝不存在，一切都被允许，魔鬼便进入了人的灵魂。", gradient: "from-red-900 via-black to-gray-800" },
  { id: "chekhov-stories", title: "契诃夫短篇小说选", titleEn: "Selected Stories", author: "安东·契诃夫", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "心理"], year: 1904, excerpt: "'在短篇小说中，重要的是像在舞台上一样——不要有任何一个多余的细节。'契诃夫以'客观性'将短篇小说提升到了抒情诗的精度。《带小狗的女人》《第六病室》——每一篇都是对灵魂的一瞥。", gradient: "from-brown-400 via-amber-300 to-gold-200" },
  { id: "mother-gorky", title: "母亲", titleEn: "Mother", author: "马克西姆·高尔基", country: "俄国", flag: "🇷🇺", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "历史"], year: 1906, excerpt: "被认为是社会主义现实主义文学的开山之作。一个普通的俄国母亲在儿子投身革命的过程中逐渐觉醒——个体的成长与时代的洪流交织成了震撼人心的叙事。", gradient: "from-red-700 via-gray-500 to-black" },
  { id: "doctor-zhivago", title: "日瓦戈医生", titleEn: "Doctor Zhivago", author: "鲍里斯·帕斯捷尔纳克", country: "俄国/苏联", flag: "🇷🇺", continent: "europe", era: "当代 (1950—)", genre: ["小说", "诗歌"], themes: ["历史", "爱情", "哲学"], year: 1957, excerpt: "以俄国革命与内战为背景，日瓦戈以诗人的敏感在历史洪流中守护着个人的尊严与爱。帕斯捷尔纳克因此书被苏联禁止领取诺贝尔奖。", gradient: "from-white via-blue-100 to-red-200" },
  { id: "one-day-ivan", title: "伊万·杰尼索维奇的一天", titleEn: "One Day in the Life of Ivan Denisovich", author: "亚历山大·索尔仁尼琴", country: "苏联", flag: "🇷🇺", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "哲学"], year: 1962, excerpt: "斯大林劳改营中一个囚犯的'平常一天'。索尔仁尼琴以最简洁的叙述打开了一座冰山——那冰山下是整个古拉格群岛。赫鲁晓夫亲自批准出版——这是苏联文学史上最惊人的'解冻'事件。", gradient: "from-white via-gray-200 to-black" },
  { id: "the-master-and-margarita", title: "大师与玛格丽特", titleEn: "The Master and Margarita", author: "米哈伊尔·布尔加科夫", country: "苏联", flag: "🇷🇺", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["魔幻", "哲学", "爱情"], year: 1966, excerpt: "魔鬼沃兰德带着随从来到了苏联时期的莫斯科，搅得天翻地覆。布尔加科夫的遗作以魔幻的笔触将政治讽刺与宗教沉思融为一体——'手稿是烧不掉的。'", gradient: "from-black via-purple-800 to-red-600" },

  // ===== 德国/奥地利 (25+) =====
  { id: "the-sorrows-of-young-werther", title: "少年维特的烦恼", titleEn: "The Sorrows of Young Werther", author: "歌德", country: "德国", flag: "🇩🇪", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "心理", "哲学"], year: 1774, excerpt: "一封封书信中，维特的爱恋逐渐走向不可挽回的终点。这本书掀起了欧洲的'维特热'——青年们穿着维特的蓝外套黄马甲，有的甚至效仿了维特的结局。", gradient: "from-blue-500 via-yellow-400 to-green-300" },
  { id: "wuthering-heights-em", title: "呼啸山庄", titleEn: "Wuthering Heights", author: "艾米莉·勃朗特", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "心理", "自然"], year: 1847, excerpt: "（已在核心库中）", gradient: "from-slate-700 via-gray-800 to-purple-900" },
  { id: "effi-briest", title: "艾菲·布里斯特", titleEn: "Effi Briest", author: "台奥多尔·冯塔纳", country: "德国", flag: "🇩🇪", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "爱情", "心理"], year: 1896, excerpt: "德国现实主义小说的顶峰。十七岁的艾菲嫁给了一位比她年长一倍的男人，多年后一段早年的'轻佻'被揭露——冯塔纳以最精确的笔触描绘了普鲁士社会的冷酷道德。", gradient: "from-blue-500 via-gray-300 to-rose-300" },
  { id: "buddenbrooks", title: "布登勃洛克一家", titleEn: "Buddenbrooks", author: "托马斯·曼", country: "德国", flag: "🇩🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 1901, excerpt: "一个北德商业家族四代人的兴衰史。托马斯·曼在二十五岁时写出了这部获诺贝尔奖的杰作——'一个家庭的没落'就是整个十九世纪资产阶级精神的没落。", gradient: "from-amber-600 via-brown-500 to-stone-400" },
  { id: "steppenwolf", title: "荒原狼", titleEn: "Steppenwolf", author: "赫尔曼·黑塞", country: "德国", flag: "🇩🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学"], year: 1927, excerpt: "哈里·哈勒尔——一头误入现代文明社会的'荒原狼'——在市民性与野性之间痛苦分裂。黑塞以一部'灵魂的自传'写尽了现代知识分子的精神困境。", gradient: "from-gray-700 via-slate-500 to-indigo-400" },
  { id: "the-glass-bead-game", title: "玻璃球游戏", titleEn: "The Glass Bead Game", author: "赫尔曼·黑塞", country: "德国", flag: "🇩🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["哲学", "宗教", "心理"], year: 1943, excerpt: "黑塞获诺贝尔奖的收官之作。在一个虚构的未来精英'卡斯塔里亚省'中，学者们以'玻璃球游戏'连接一切人类知识——但克乃西特大师最终选择离开象牙塔。", gradient: "from-teal-500 via-glass-300 to-purple-300" },
  { id: "the-tin-drum", title: "铁皮鼓", titleEn: "The Tin Drum", author: "君特·格拉斯", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "魔幻", "社会"], year: 1959, excerpt: "奥斯卡·马策拉特——一个三岁就决定不再长高的侏儒——以他的铁皮鼓和能震碎玻璃的尖叫作为武器，'击打'出了一部二十世纪德国史。", gradient: "from-red-600 via-white-500 to-black" },
  { id: "the-reader", title: "朗读者", titleEn: "The Reader", author: "本哈德·施林克", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "历史", "心理"], year: 1995, excerpt: "十五岁的少年与三十六岁的电车售票员汉娜的夏日之恋多年后在法庭上重逢——汉娜作为纳粹战犯受审。关于罪与耻、爱与罚的深刻沉思。", gradient: "from-green-500 via-blue-400 to-gray-300" },

  // ===== 意大利 (15+) =====
  { id: "the-prince", title: "君主论", titleEn: "The Prince", author: "尼可罗·马基雅维利", country: "意大利", flag: "🇮🇹", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["哲学", "散文/随笔"], themes: ["哲学", "社会", "历史"], year: 1513, excerpt: "'被畏惧比被爱戴更安全'——五百年来的政治哲学都在回应或反驳这句话。马基雅维利将政治从道德神学中剥离——这是现代政治思想的出生证明。", gradient: "from-red-800 via-black to-gold-400" },
  { id: "orlando-furioso", title: "疯狂的奥兰多", titleEn: "Orlando Furioso", author: "阿里奥斯托", country: "意大利", flag: "🇮🇹", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["史诗", "诗歌"], themes: ["爱情", "战争", "魔幻"], year: 1532, excerpt: "查理大帝麾下的骑士奥兰多因失恋而发疯——阿里奥斯托以四千多行八行体编织了一幅骑士、魔法、爱情与战争构成的瑰丽画卷。", gradient: "from-purple-500 via-rose-400 to-gold-300" },
  { id: "jerusalem-delivered", title: "被解放的耶路撒冷", titleEn: "Jerusalem Delivered", author: "塔索", country: "意大利", flag: "🇮🇹", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["史诗", "诗歌"], themes: ["战争", "宗教", "爱情"], year: 1581, excerpt: "以第一次十字军东征为背景的史诗。塔索在宗教虔诚与浪漫爱情之间的张力中塑造了一种独特的哀伤——'正是这种哀伤使《被解放的耶路撒冷》区别于所有其他史诗。'", gradient: "from-blue-700 via-red-600 to-gold-500" },
  { id: "the-betrothed", title: "约婚夫妇", titleEn: "The Betrothed", author: "亚历山德罗·曼佐尼", country: "意大利", flag: "🇮🇹", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["爱情", "社会", "宗教"], year: 1840, excerpt: "意大利第一部现代小说。十七世纪米兰大瘟疫背景下两个恋人的辗转流离——曼佐尼以这部历史小说为意大利文学确立了现代标准。", gradient: "from-green-600 via-white-400 to-red-500" },
  { id: "confessions-of-zeno", title: "泽诺的意识", titleEn: "Confessions of Zeno", author: "伊塔洛·斯韦沃", country: "意大利", flag: "🇮🇹", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学"], year: 1923, excerpt: "'我最后一次吸烟了'——这句话贯穿了整部'戒烟日记'。泽诺以精神分析的自我审视揭开了意识中无尽的自我欺骗。乔伊斯是最早发现这部杰作的读者之一。", gradient: "from-brown-400 via-amber-300 to-gray-200" },
  { id: "if-on-a-winters-night", title: "如果在冬夜，一个旅人", titleEn: "If on a Winter's Night a Traveler", author: "伊塔洛·卡尔维诺", country: "意大利", flag: "🇮🇹", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "爱情"], year: 1979, excerpt: "一部关于'阅读'本身的小说。'你'——读者——买了一本卡尔维诺的新书，却发现只有开头不断重新开始……十本只有开头的小说嵌套在一个追寻它们结尾的故事中。", gradient: "from-indigo-500 via-purple-400 to-pink-300" },
  { id: "the-name-of-the-rose", title: "玫瑰的名字", titleEn: "The Name of the Rose", author: "翁贝托·艾柯", country: "意大利", flag: "🇮🇹", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "宗教", "冒险"], year: 1980, excerpt: "中世纪修道院中的连环谋杀案，以符号学家威廉修士的探案为线索——艾柯将侦探小说、神学辩论与符号学理论编织成一部知识分子的惊险小说。", gradient: "from-stone-600 via-rose-700 to-gold-500" },

  // ===== 西班牙/葡萄牙 (15+) =====
  { id: "la-celestina", title: "塞莱斯蒂娜", titleEn: "La Celestina", author: "费尔南多·德·罗哈斯", country: "西班牙", flag: "🇪🇸", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["戏剧", "小说"], themes: ["爱情", "社会", "心理"], year: 1499, excerpt: "一部以对话体写成的前所未有的作品——既是戏剧又是小说。老鸨塞莱斯蒂娜操纵着一对贵族青年的爱情，最终所有人都被欲望的网缠死。", gradient: "from-red-800 via-amber-600 to-black" },
  { id: "lazarillo-de-tormes", title: "小癞子", titleEn: "Lazarillo de Tormes", author: "佚名", country: "西班牙", flag: "🇪🇸", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["小说"], themes: ["社会", "冒险"], year: 1554, excerpt: "流浪汉小说的开山之作。瞎子、教士、乡绅、修士——小癞子换了一个又一个主人，在饥饿中学会了生存的狡猾。'您让我喝一口吧'——每一个主人都在压榨他。", gradient: "from-amber-500 via-brown-400 to-gray-300" },
  { id: "life-is-a-dream", title: "人生如梦", titleEn: "Life Is a Dream", author: "卡尔德隆·德·拉·巴尔卡", country: "西班牙", flag: "🇪🇸", continent: "europe", era: "文艺复兴 (1500—1700)", genre: ["戏剧"], themes: ["哲学", "心理"], year: 1635, excerpt: "波兰王子塞西斯蒙多一生都被囚禁在塔中——因为预言说他将成为暴君。当他被麻醉后带入王宫时，他分不清这是梦还是醒。'人生是什么？一场疯狂，一个虚幻。'", gradient: "from-blue-800 via-purple-700 to-gold-500" },
  { id: "gypsy-ballads", title: "吉普赛谣曲集", titleEn: "Gypsy Ballads", author: "费德里科·加西亚·洛尔迦", country: "西班牙", flag: "🇪🇸", continent: "europe", era: "现代 (1900—1950)", genre: ["诗歌"], themes: ["爱情", "社会", "自然"], year: 1928, excerpt: "洛尔迦以安达卢西亚的深歌传统为根基，将吉普赛文化与超现实主义意象融合为一部令人心魂荡漾的诗集。'绿色，我多么爱你这绿色。'", gradient: "from-green-500 via-olive-400 to-gold-300" },
  { id: "the-book-of-disquiet", title: "不安之书", titleEn: "The Book of Disquiet", author: "费尔南多·佩索阿", country: "葡萄牙", flag: "🇵🇹", continent: "europe", era: "现代 (1900—1950)", genre: ["散文/随笔"], themes: ["哲学", "心理"], year: 1982, excerpt: "佩索阿以'半异名者'贝尔纳多·索阿雷斯的身份写下的碎片之书——'我的一生是一次无休止的失败。'但这些'失败'的碎片拼出了二十世纪最伟大的散文作品。", gradient: "from-gray-500 via-blue-300 to-white" },
  { id: "blindness", title: "失明症漫记", titleEn: "Blindness", author: "若泽·萨拉马戈", country: "葡萄牙", flag: "🇵🇹", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "哲学", "心理"], year: 1995, excerpt: "整座城市的人突然都失明了——只有一个人例外。萨拉马戈以一种不带分段标记的独特文体将读者抛入文明崩溃之后的至暗与微光之中。", gradient: "from-white via-gray-300 to-black" },

  // ===== 北欧 (15+) =====
  { id: "njalssaga", title: "尼雅尔传", titleEn: "Njál's Saga", author: "佚名", country: "冰岛", flag: "🇮🇸", continent: "europe", era: "中世纪 (500—1500)", genre: ["史诗", "小说"], themes: ["社会", "历史", "哲学"], year: 1280, excerpt: "冰岛萨迦文学的最高成就。一场由邻里纠纷引发的血腥世仇——尼雅尔以法律和智慧试图平息冲突，却最终与家人一同被烧死在家中。'冰岛的荷马'创造的北欧悲剧。", gradient: "from-white via-blue-200 to-black" },
  { id: "peer-gynt", title: "培尔·金特", titleEn: "Peer Gynt", author: "亨利克·易卜生", country: "挪威", flag: "🇳🇴", continent: "europe", era: "近代 (1700—1900)", genre: ["戏剧", "诗歌"], themes: ["冒险", "心理", "哲学"], year: 1867, excerpt: "培尔·金特——一个永远在逃避'自我'的浪子——从挪威山谷到摩洛哥沙漠再到疯人院，最终在老年的归途中面对一个残酷的问题：你这一生，到底成为过你自己吗？", gradient: "from-green-600 via-snow-200 to-blue-400" },
  { id: "hunger", title: "饥饿", titleEn: "Hunger", author: "克努特·汉姆生", country: "挪威", flag: "🇳🇴", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["心理", "社会"], year: 1890, excerpt: "一个匿名的年轻作家在克里斯蒂安尼亚（今奥斯陆）的饥饿边缘挣扎。汉姆生以第一人称的意识流（早于乔伊斯三十年）将饥饿如何扭曲和锐化人的心智写得入骨三分。", gradient: "from-gray-500 via-amber-300 to-red-200" },
  { id: "pippi-longstocking", title: "长袜子皮皮", titleEn: "Pippi Longstocking", author: "阿斯特丽德·林格伦", country: "瑞典", flag: "🇸🇪", continent: "europe", era: "当代 (1950—)", genre: ["民间故事"], themes: ["冒险", "社会"], year: 1945, excerpt: "一个九岁女孩、一匹马、一只猴子、一整箱金币——皮皮以她的超人之力颠覆了成人世界的所有规则。这是写给所有拒绝'长大'的孩子的快乐宣言。", gradient: "from-red-500 via-orange-400 to-yellow-300" },

  // ===== 东欧 (25+) =====
  { id: "the-good-soldier-svejk", title: "好兵帅克", titleEn: "The Good Soldier Švejk", author: "雅罗斯拉夫·哈谢克", country: "捷克", flag: "🇨🇿", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["战争", "社会"], year: 1923, excerpt: "帅克——一个看似白痴的捷克士兵——以他的'绝对服从'将奥匈帝国的军事官僚体制变成了全欧洲最庞大的笑话机器。'向皇帝陛下效忠，直到最后一滴油。'", gradient: "from-green-500 via-gold-400 to-red-300" },
  { id: "the-unbearable-lightness", title: "不能承受的生命之轻", titleEn: "The Unbearable Lightness of Being", author: "米兰·昆德拉", country: "捷克/法国", flag: "🇨🇿", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "爱情", "历史"], year: 1984, excerpt: "'最沉重的负担同时也是最强盛的生命力的影像。'托马斯、特蕾莎、萨宾娜——在1968年布拉格之春的背景下，昆德拉以这部'音乐性小说'追问了轻与重、偶然与必然。", gradient: "from-blue-600 via-gray-400 to-rose-300" },
  { id: "the-joke", title: "玩笑", titleEn: "The Joke", author: "米兰·昆德拉", country: "捷克", flag: "🇨🇿", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "爱情"], year: 1967, excerpt: "一张明信片上的玩笑话毁了一个人的一生。昆德拉的处女作以多人称叙述拼接出一个关于斯大林时代捷克社会的'残酷笑话'。", gradient: "from-gray-600 via-red-400 to-black" },
  { id: "quovadis", title: "你往何处去", titleEn: "Quo Vadis", author: "亨利克·显克维支", country: "波兰", flag: "🇵🇱", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["历史", "宗教", "爱情"], year: 1896, excerpt: "尼禄时代的罗马——基督徒在地下墓穴中坚守信仰，暴君在宫殿中焚烧城市。显克维支以这部史诗性的历史小说获得了诺贝尔文学奖。", gradient: "from-red-800 via-gold-500 to-purple-600" },
  { id: "solaris", title: "索拉里斯星", titleEn: "Solaris", author: "斯坦尼斯瓦夫·莱姆", country: "波兰", flag: "🇵🇱", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理"], year: 1961, excerpt: "索拉里斯星的海洋是一个有意识的存在，它从宇航员的记忆中'制造'出他们最深的愧疚与渴望。莱姆以科幻为壳追问：人类真的有能力理解'非人类'的智慧吗？", gradient: "from-blue-900 via-ocean-500 to-white" },
];
