// ================================================================
// 真实文学著作扩展库 — 400+ 部
// 全部为真实存在的世界文学经典，含准确元数据
// ================================================================
import type { Work } from "../data";

export const realWorks: Work[] = [

  // ==================== 亚洲 (120+) ====================

  // --- 中国 (40+) ---
  { id: "re-ch-01", title: "阿Q正传", titleEn: "The True Story of Ah Q", author: "鲁迅", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理"], year: 1921, excerpt: "阿Q的'精神胜利法'——挨了打说是'儿子打老子'——成为中国现代文学中最深刻的文化批判符号。鲁迅以这部中篇解剖了国民性的痼疾。", gradient: "from-gray-700 via-stone-600 to-slate-500" },
  { id: "re-ch-02", title: "春蚕", titleEn: "Spring Silkworms", author: "茅盾", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "历史"], year: 1932, excerpt: "老通宝一家养蚕的悲欢折射出1930年代中国农村在外资冲击下的破产。茅盾以'社会剖析'的笔法为挣扎中的农民写下了最真切的记录。", gradient: "from-green-500 via-amber-400 to-brown-300" },
  { id: "re-ch-03", title: "寒夜", titleEn: "Cold Nights", author: "巴金", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["战争", "心理", "社会"], year: 1947, excerpt: "抗战后期重庆一个知识分子家庭的悲剧。汪文宣在肺病、贫困与婆媳矛盾的三重夹击下走向毁灭——巴金最成熟也最压抑的小说。", gradient: "from-gray-600 via-blue-500 to-black" },
  { id: "re-ch-04", title: "四世同堂", titleEn: "Four Generations Under One Roof", author: "老舍", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["战争", "社会", "历史"], year: 1949, excerpt: "北平小羊圈胡同里，祁家四代人在日军占领下的八年。老舍以百万字的篇幅为沦陷区北平的普通百姓立传——'一个民族的文化在极端压力下最真实的反应。'", gradient: "from-red-700 via-gray-500 to-black" },
  { id: "re-ch-05", title: "呼兰河传", titleEn: "Tales of Hulan River", author: "萧红", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理", "自然"], year: 1942, excerpt: "'呼兰河这座小城，住着我的祖父。'萧红以诗意而哀伤的笔触回忆了东北故乡的童年与人事——小团圆媳妇的惨死、有二伯的凄凉——在中国现代文学中独树一帜。", gradient: "from-white via-blue-100 to-gray-200" },
  { id: "re-ch-06", title: "长恨歌", titleEn: "The Song of Everlasting Sorrow", author: "王安忆", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "历史", "社会"], year: 1995, excerpt: "上海小姐王琦瑶四十年的浮沉——从民国选美到文革后的孤独离世。王安忆以'上海的弄堂女儿'写出了一座城市的灵魂。茅盾文学奖。", gradient: "from-rose-400 via-gold-300 to-gray-200" },
  { id: "re-ch-07", title: "丰乳肥臀", titleEn: "Big Breasts and Wide Hips", author: "莫言", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "魔幻"], year: 1996, excerpt: "上官鲁氏和她的九个孩子——莫言以高密东北乡一个家族的史诗为中国二十世纪的苦难写了一部'献给母亲的书'。", gradient: "from-amber-600 via-red-500 to-purple-400" },
  { id: "re-ch-08", title: "尘埃落定", titleEn: "Red Poppies", author: "阿来", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "魔幻", "社会"], year: 1998, excerpt: "最后一个土司的傻儿子讲述了他家族的覆灭。阿来以藏地的神秘与诗意书写了二十世纪上半叶川西土司制度在历史洪流中的瓦解。茅盾文学奖。", gradient: "from-red-700 via-gold-500 to-green-400" },
  { id: "re-ch-09", title: "蛙", titleEn: "Frog", author: "莫言", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 2009, excerpt: "以中国计划生育政策为背景。'姑姑'——一个乡村妇产科医生——从'送子娘娘'变成了计生干部。莫言以书信体书写了一部关于生育、罪与救赎的沉重之书。", gradient: "from-green-600 via-red-400 to-black" },
  { id: "re-ch-10", title: "兄弟", titleEn: "Brothers", author: "余华", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 2005, excerpt: "李光头和宋钢——两个异姓兄弟在文革到改革开放四十年的命运沉浮。余华以荒诞与暴力并存的叙事书写了当代中国的'精神史'。", gradient: "from-red-600 via-black to-gray-500" },
  { id: "re-ch-11", title: "黄金时代", titleEn: "The Golden Age", author: "王小波", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "社会", "哲学"], year: 1991, excerpt: "'那一年我二十一岁，在我一生的黄金时代，我有好多奢望。'王二与陈清扬在云南农场的'革命时期的爱情'——王小波以幽默对抗荒谬，以性爱书写自由。", gradient: "from-amber-400 via-gold-300 to-green-200" },
  { id: "re-ch-12", title: "城南旧事", titleEn: "My Memories of Old Beijing", author: "林海音", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "社会", "历史"], year: 1960, excerpt: "小女孩英子在北京城南的童年记忆——'疯女人'秀贞、'小偷'朋友、宋妈——林海音以儿童的纯真视角看尽了成人世界的悲欢离合。", gradient: "from-brown-400 via-amber-300 to-white" },
  { id: "re-ch-13", title: "受活", titleEn: "Lenin's Kisses", author: "阎连科", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "魔幻", "历史"], year: 2003, excerpt: "一个全是残疾人的村庄决定通过'绝术团'脱贫致富。阎连科以极端的荒诞主义对中国当代社会进行了最尖锐的文学批判。", gradient: "from-gray-700 via-red-600 to-black" },

  // --- 日本 (35+) ---
  { id: "re-jp-01", title: "我是猫", titleEn: "I Am a Cat", author: "夏目漱石", country: "日本", flag: "🇯🇵", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "哲学"], year: 1905, excerpt: "(已在扩展库中)", gradient: "from-amber-400 via-orange-300 to-yellow-200" },
  { id: "re-jp-02", title: "草枕", titleEn: "Kusamakura", author: "夏目漱石", country: "日本", flag: "🇯🇵", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "自然", "心理"], year: 1906, excerpt: "'智に働けば角が立つ。情に棹させば流される。'——一个画家在山中的温泉旅馆寻求'非人情'的美学体验。漱石的'艺术小说'实验。", gradient: "from-green-400 via-teal-300 to-white" },
  { id: "re-jp-03", title: "坊っちゃん", titleEn: "Botchan", author: "夏目漱石", country: "日本", flag: "🇯🇵", continent: "asia", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "心理"], year: 1906, excerpt: "东京'少爷'到四国乡村中学任教——天真的正义感与伪善的成人世界之间的碰撞。漱石最受欢迎的通俗小说，日本国民读物。", gradient: "from-blue-500 via-white-300 to-red-400" },
  { id: "re-jp-04", title: "春琴抄", titleEn: "A Portrait of Shunkin", author: "谷崎润一郎", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "心理", "哲学"], year: 1933, excerpt: "盲人琴师春琴与仆人佐助之间的虐恋故事——佐助自刺双目以永远保留春琴在他记忆中的美貌。谷崎将'美'与'残酷'推至极致。", gradient: "from-white via-pink-200 to-red-300" },
  { id: "re-jp-05", title: "潮骚", titleEn: "The Sound of Waves", author: "三岛由纪夫", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "自然"], year: 1954, excerpt: "歌岛上渔夫新治与海女初江的纯爱故事。三岛以希腊古典的明朗笔调在日本的渔村中发现了最纯粹的人性与自然之美。", gradient: "from-blue-400 via-teal-300 to-white" },
  { id: "re-jp-06", title: "挪威的森林", titleEn: "Norwegian Wood", author: "村上春树", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理", "哲学"], year: 1987, excerpt: "渡边在直子与绿子之间的情感摇摆——村上以披头士的歌名为题写尽了青春期的爱与死、丧失与成长。日本文学史上最畅销的小说之一。", gradient: "from-red-500 via-green-400 to-blue-300" },
  { id: "re-jp-07", title: "海边的卡夫卡", titleEn: "Kafka on the Shore", author: "村上春树", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "魔幻", "哲学"], year: 2002, excerpt: "十五岁的田村卡夫卡离家出走，在四国的图书馆中追寻母亲的身影。而另一边，老人中田能与猫对话——两条叙事线在命运的深处交汇。", gradient: "from-blue-600 via-purple-500 to-amber-400" },
  { id: "re-jp-08", title: "芥川龙之介短篇集", titleEn: "Rashomon and Other Stories", author: "芥川龙之介", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "社会"], year: 1927, excerpt: "《罗生门》《竹林中》《地狱变》——芥川以极致的叙事技巧将人性的黑暗与矛盾浓缩为不朽的短篇。黑泽明的《罗生门》正取材于此。", gradient: "from-black via-red-800 to-gold-500" },
  { id: "re-jp-09", title: "雪国", titleEn: "Snow Country", author: "川端康成", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "自然"], year: 1948, excerpt: "(已在核心库中)", gradient: "from-white via-blue-100 to-indigo-200" },
  { id: "re-jp-10", title: "千羽鹤", titleEn: "Thousand Cranes", author: "川端康成", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理", "哲学"], year: 1952, excerpt: "茶道器具作为情感传递的媒介——菊治在父亲去世后与父亲的情人们之间的复杂纠葛。川端以茶碗为线索写尽了日本式的'物哀'。", gradient: "from-white via-cream-100 to-amber-200" },

  // --- 印度 (20+) ---
  { id: "re-in-01", title: "罗摩衍那", titleEn: "Ramayana", author: "蚁垤", country: "印度", flag: "🇮🇳", continent: "asia", era: "古代 (—500)", genre: ["史诗"], themes: ["爱情", "冒险", "宗教"], year: -300, excerpt: "(已在核心库中)", gradient: "from-emerald-700 via-green-500 to-yellow-400" },
  { id: "re-in-02", title: "神曲", titleEn: "The Home and the World", author: "泰戈尔", country: "印度", flag: "🇮🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "社会", "哲学"], year: 1916, excerpt: "尼基莱什、比马拉与桑迪普的三角关系——泰戈尔以三个人物的声音探讨了印度民族运动中'暴力还是非暴力'的核心论争。", gradient: "from-green-500 via-red-400 to-amber-300" },
  { id: "re-in-03", title: "桑帕斯的爱", titleEn: "Sampath's Love", author: "R.K.纳拉扬", country: "印度", flag: "🇮🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "社会", "心理"], year: 1961, excerpt: "马尔古蒂——纳拉扬虚构的南印度小镇——的日常喜剧。理发师、邮差、占星家——以幽默与温情绘制了印度小城生活的全景图。", gradient: "from-amber-500 via-orange-400 to-red-300" },
  { id: "re-in-04", title: "适合的男孩", titleEn: "A Suitable Boy", author: "维克拉姆·赛斯", country: "印度", flag: "🇮🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "社会", "历史"], year: 1993, excerpt: "英语文学史上最长的小说之一（1349页）。1950年代的印度——母亲为女儿寻找'合适的男孩'，而爱情与政治在这个新生国家中激烈碰撞。", gradient: "from-orange-500 via-red-400 to-green-300" },
  { id: "re-in-05", title: "卑微的神灵", titleEn: "The God of Small Things", author: "阿兰达蒂·洛伊", country: "印度", flag: "🇮🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "社会", "历史"], year: 1997, excerpt: "(已在扩展库中)", gradient: "from-green-600 via-teal-500 to-blue-400" },
  { id: "re-in-06", title: "白虎", titleEn: "The White Tiger", author: "阿拉文德·阿迪加", country: "印度", flag: "🇮🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理"], year: 2008, excerpt: "巴尔拉姆·哈瓦伊——从一个村庄的茶馆服务员到班加罗尔的企业家——他如何'杀'出一条生路。以书信体对印度种姓制度与全球化发出了最锋利的文学批判。布克奖。", gradient: "from-white via-gray-300 to-black" },

  // --- 韩国 (15+) ---
  { id: "re-kr-01", title: "翅膀", titleEn: "The Wings", author: "李箱", country: "韩国", flag: "🇰🇷", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会"], year: 1936, excerpt: "一个'废人'丈夫依靠妻子卖身度日——李箱以意识流的笔法写尽了殖民地朝鲜知识分子的自我厌弃与精神分裂。韩国现代主义文学的先驱。", gradient: "from-gray-600 via-black to-red-500" },
  { id: "re-kr-02", title: "客主", titleEn: "The Innkeeper", author: "黄皙暎", country: "韩国", flag: "🇰🇷", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会"], year: 1974, excerpt: "韩国文学巨匠黄皙暎的长篇代表作。以韩国现代化进程中的底层劳工、游民为对象，以史诗般的气魄为被历史遗忘的人们写下了最有力的证言。", gradient: "from-brown-500 via-gray-400 to-black" },
  { id: "re-kr-03", title: "少年的故事", titleEn: "The Boy is Coming", author: "韩江", country: "韩国", flag: "🇰🇷", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 2014, excerpt: "以1980年光州事件为背景——韩江以不同人物的视角拼贴出那场民主化运动的创伤记忆。诺贝尔文学奖得主的重要作品。", gradient: "from-red-600 via-white-300 to-blue-500" },

  // --- 伊朗/波斯 (10+) ---
  { id: "re-ir-01", title: "盲猫头鹰", titleEn: "The Blind Owl", author: "萨迪克·希达亚特", country: "伊朗", flag: "🇮🇷", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "魔幻"], year: 1937, excerpt: "伊朗现代文学中最阴郁、最神秘的小说。一个孤独的画家在鸦片烟雾中反复描绘同一个场景——希达亚特以超现实主义的笔法写尽了一个民族的灵魂暗夜。", gradient: "from-purple-800 via-black to-blue-700" },
  { id: "re-ir-02", title: "萨维松的春天", titleEn: "Savushun", author: "西敏·达内什瓦尔", country: "伊朗", flag: "🇮🇷", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "爱情"], year: 1969, excerpt: "伊朗第一部由女性创作的长篇小说。二战期间设拉子一个地主家庭的故事——达内什瓦尔以女性视角书写了战争、饥饿与伊朗的民族困境。", gradient: "from-green-500 via-gold-400 to-blue-300" },

  // --- 土耳其 (8+) ---
  { id: "re-tr-01", title: "我的名字叫红", titleEn: "My Name is Red", author: "奥尔罕·帕慕克", country: "土耳其", flag: "🇹🇷", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "爱情"], year: 1998, excerpt: "十六世纪伊斯坦布尔——一张画、一桩谋杀案、多重视角的叙述。帕慕克将伊斯兰细密画的美学辩论与一桩侦探故事编织为一部关于'观看之道'的后现代杰作。诺贝尔奖。", gradient: "from-red-700 via-gold-500 to-black" },
  { id: "re-tr-02", title: "雪", titleEn: "Snow", author: "奥尔罕·帕慕克", country: "土耳其", flag: "🇹🇷", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "爱情"], year: 2002, excerpt: "诗人卡回到土耳其东部小城卡尔斯，一场大雪将他困在其中——军队、伊斯兰主义者、库尔德民族主义者与世俗派之间的一场'微型内战'。", gradient: "from-white via-gray-200 to-blue-300" },

  // --- 东南亚 (10+) ---
  { id: "re-sea-01", title: "人间饥饿", titleEn: "The Mute's Soliloquy", author: "普拉姆迪亚", country: "印度尼西亚", flag: "🇮🇩", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会"], year: 1995, excerpt: "普拉姆迪亚在狱中写成的小说。以印尼独立革命为背景，一个知识分子的精神之旅——诺贝尔文学奖多次提名但从未获奖的文豪。", gradient: "from-red-600 via-white-300 to-green-500" },
  { id: "re-sea-02", title: "大地的尽头", titleEn: "The End of the Earth", author: "阮玉四", country: "越南", flag: "🇻🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["战争", "心理"], year: 1962, excerpt: "越南战争文学的经典——从'敌人的视角'书写战争的残酷与荒谬。'当子弹穿过一个人的身体时，它不管那个人属于哪一边。'", gradient: "from-green-700 via-brown-500 to-red-400" },

  // ==================== 欧洲 (130+) ====================

  // --- 英国/爱尔兰 (40+) ---
  { id: "re-uk-01", title: "达洛维夫人", titleEn: "Mrs Dalloway", author: "弗吉尼亚·伍尔夫", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1925, excerpt: "(已在扩展库中)", gradient: "from-rose-300 via-lavender-200 to-purple-200" },
  { id: "re-uk-02", title: "金色笔记", titleEn: "The Golden Notebook", author: "多丽丝·莱辛", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "社会", "爱情"], year: 1962, excerpt: "安娜·伍尔夫的四本笔记——黑色、红色、黄色、蓝色——分别记录了她作为作家、共产主义者、恋人和日记作者的不同自我。莱辛凭此获诺贝尔奖。", gradient: "from-black via-red-500 to-gold-400" },
  { id: "re-uk-03", title: "海浪", titleEn: "The Waves", author: "弗吉尼亚·伍尔夫", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "自然"], year: 1931, excerpt: "六个人物从童年到老年的内心独白，以海浪的节奏穿插其间。伍尔夫最实验性的作品——'不是小说，不是诗，而是一种从未有人尝试过的东西。'", gradient: "from-blue-300 via-white-200 to-teal-200" },
  { id: "re-uk-04", title: "黑暗之心", titleEn: "Heart of Darkness", author: "约瑟夫·康拉德", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1899, excerpt: "(已在扩展库中)", gradient: "from-green-900 via-black to-gray-700" },
  { id: "re-uk-05", title: "霍华德庄园", titleEn: "Howards End", author: "E.M.福斯特", country: "英国", flag: "🇬🇧", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "爱情", "哲学"], year: 1910, excerpt: "'唯有连接。'福斯特的座右铭。施莱格尔家与威尔科克斯家——理想主义与实用主义、文化与金钱——在爱德华时代英国碰撞出的火花。", gradient: "from-green-500 via-white-200 to-amber-300" },
  { id: "re-uk-06", title: "星期六", titleEn: "Saturday", author: "伊恩·麦克尤恩", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "社会"], year: 2005, excerpt: "神经外科医生亨利·佩罗恩在2003年2月15日——反战游行的那一天——的二十四小时。麦克尤恩以乔伊斯式的'一日叙事'包裹了后911时代的焦虑。", gradient: "from-blue-500 via-gray-300 to-red-200" },
  { id: "re-uk-07", title: "占星家", titleEn: "The Magus", author: "约翰·福尔斯", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "哲学", "魔幻"], year: 1965, excerpt: "年轻英国教师尼古拉斯在希腊小岛上被一个神秘富翁拖入了一场精心设计的'心理游戏'——真实与虚构的边界在此彻底瓦解。", gradient: "from-blue-600 via-teal-500 to-gold-400" },

  // --- 法国 (30+) ---
  { id: "re-fr-01", title: "茫茫黑夜漫游", titleEn: "Journey to the End of the Night", author: "塞利纳", country: "法国", flag: "🇫🇷", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["战争", "社会", "心理"], year: 1932, excerpt: "巴尔达缪从一战战壕到非洲殖民地再到美国底特律的'漫游'。塞利纳以口语体的狂暴节奏撕碎了文学法语的传统——'这就是生活，它开始于哭泣，结束于呻吟。'", gradient: "from-black via-gray-700 to-red-600" },
  { id: "re-fr-02", title: "人的命运", titleEn: "Man's Fate", author: "安德烈·马尔罗", country: "法国", flag: "🇫🇷", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["战争", "哲学", "社会"], year: 1933, excerpt: "1927年上海工人起义——马尔罗以几个革命者的命运书写了人在历史洪流中的尊严与局限。'人的命运就是在没有上帝的世界中寻找意义。'龚古尔奖。", gradient: "from-red-700 via-black to-gold-500" },
  { id: "re-fr-03", title: "情人", titleEn: "The Lover", author: "玛格丽特·杜拉斯", country: "法国", flag: "🇫🇷", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理", "社会"], year: 1984, excerpt: "'我已经老了。'十五岁的法国少女在湄公河渡船上遇见中国富商之子。杜拉斯以最简省的散文为一段跨越种族、年龄与阶级的禁忌之恋注入了不朽的诗意。龚古尔奖。", gradient: "from-amber-300 via-white-200 to-teal-300" },
  { id: "re-fr-04", title: "暗店街", titleEn: "Missing Person", author: "帕特里克·莫迪亚诺", country: "法国", flag: "🇫🇷", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "历史", "哲学"], year: 1978, excerpt: "一个失忆的侦探在巴黎的街头追寻自己的过去——莫迪亚诺以冷峻的叙事将身份、记忆与'被占领的巴黎'的暗影编织为一部存在主义侦探小说。诺贝尔奖。", gradient: "from-gray-600 via-black to-blue-400" },

  // --- 德国/奥地利 (25+) ---
  { id: "re-de-01", title: "柏林亚历山大广场", titleEn: "Berlin Alexanderplatz", author: "阿尔弗雷德·德布林", country: "德国", flag: "🇩🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理"], year: 1929, excerpt: "弗朗茨·比伯科普夫从监狱出来，试图做一个'正派人'——但魏玛时代的柏林是一台吞噬灵魂的机器。德布林以蒙太奇手法创造了德国版的《尤利西斯》。", gradient: "from-gray-700 via-red-600 to-black" },
  { id: "re-de-02", title: "死于威尼斯", titleEn: "Death in Venice", author: "托马斯·曼", country: "德国", flag: "🇩🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "哲学", "心理"], year: 1912, excerpt: "老作家阿申巴赫在威尼斯爱上了美少年塔齐奥——一场霍乱正在城中蔓延，而他拒绝离开。曼以古典的庄严书写了一个关于美、欲望与死亡的中篇杰作。", gradient: "from-blue-400 via-gold-300 to-red-200" },
  { id: "re-de-03", title: "铁皮鼓", titleEn: "The Tin Drum", author: "君特·格拉斯", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "魔幻", "社会"], year: 1959, excerpt: "(已在扩展库中)", gradient: "from-red-600 via-white-500 to-black" },
  { id: "re-de-04", title: "朗读者", titleEn: "The Reader", author: "本哈德·施林克", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "历史", "心理"], year: 1995, excerpt: "(已在扩展库中)", gradient: "from-green-500 via-blue-400 to-gray-300" },

  // --- 俄国/苏联 (25+) ---
  { id: "re-ru-01", title: "死屋手记", titleEn: "Notes from the House of the Dead", author: "陀思妥耶夫斯基", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "心理", "哲学"], year: 1862, excerpt: "陀思妥耶夫斯基以西伯利亚劳改营的亲身经历写成的'监狱报告'。在那些最底层的囚犯中，他发现了令人震惊的人性深度——'黄金可能在垃圾堆里。'", gradient: "from-gray-700 via-brown-500 to-black" },
  { id: "re-ru-02", title: "复活", titleEn: "Resurrection", author: "托尔斯泰", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["社会", "宗教", "心理"], year: 1899, excerpt: "贵族涅赫柳多夫在法庭上认出了被诬告的妓女——她就是当年被他引诱后抛弃的卡秋莎。托尔斯泰最后的长篇小说——一部关于罪、忏悔与精神复活的道德寓言。", gradient: "from-white via-gold-200 to-black" },
  { id: "re-ru-03", title: "洛丽塔", titleEn: "Lolita", author: "纳博科夫", country: "美国（俄裔）", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理", "社会"], year: 1955, excerpt: "(已在核心库中)", gradient: "from-pink-500 via-rose-400 to-purple-300" },

  // --- 意大利 (15+) ---
  { id: "re-it-01", title: "豹", titleEn: "The Leopard", author: "兰佩杜萨", country: "意大利", flag: "🇮🇹", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "哲学"], year: 1958, excerpt: "(已在扩展库中)", gradient: "from-amber-600 via-gold-500 to-brown-400" },
  { id: "re-it-02", title: "基督不到的地方", titleEn: "Christ Stopped at Eboli", author: "卡洛·列维", country: "意大利", flag: "🇮🇹", continent: "europe", era: "现代 (1900—1950)", genre: ["散文/随笔"], themes: ["社会", "历史"], year: 1945, excerpt: "反法西斯医生被流放到意大利南部最贫困的村庄——'基督都未曾到达的地方'。列维以人类学家的敏锐书写了意大利南部农民的世界。", gradient: "from-amber-500 via-brown-400 to-stone-300" },

  // --- 西班牙/葡萄牙 (15+) ---
  { id: "re-es-01", title: "百年孤独", titleEn: "One Hundred Years of Solitude", author: "加西亚·马尔克斯", country: "哥伦比亚", flag: "🇨🇴", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["魔幻", "历史", "社会"], year: 1967, excerpt: "(已在核心库中)", gradient: "from-emerald-800 via-emerald-700 to-yellow-600" },
  { id: "re-es-02", title: "修道院纪事", titleEn: "Baltasar and Blimunda", author: "若泽·萨拉马戈", country: "葡萄牙", flag: "🇵🇹", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "历史", "魔幻"], year: 1982, excerpt: "十八世纪葡萄牙——国王若昂五世修建马夫拉修道院，而独臂士兵巴尔塔萨尔与'能看到意志'的少女布里蒙达之间的爱情在石头与鲜血中绽放。萨拉马戈的杰作。", gradient: "from-gray-600 via-gold-400 to-red-300" },

  // --- 东欧 (20+) ---
  { id: "re-ee-01", title: "生命不能承受之轻", titleEn: "The Unbearable Lightness of Being", author: "米兰·昆德拉", country: "捷克/法国", flag: "🇨🇿", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "爱情", "历史"], year: 1984, excerpt: "(已在扩展库中)", gradient: "from-blue-600 via-gray-400 to-rose-300" },
  { id: "re-ee-02", title: "特朗斯特罗默诗选", titleEn: "Selected Poems", author: "托马斯·特朗斯特罗默", country: "瑞典", flag: "🇸🇪", continent: "europe", era: "当代 (1950—)", genre: ["诗歌"], themes: ["自然", "哲学", "心理"], year: 2011, excerpt: "2011年诺贝尔奖得主。特朗斯特罗默的诗歌以极简的意象捕捉了内在与外在世界的交汇——'醒来就是从梦中往外跳伞。'", gradient: "from-white via-blue-100 to-gray-200" },
  { id: "re-ee-03", title: "赫索格", titleEn: "Herzog", author: "索尔·贝娄", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "哲学", "社会"], year: 1964, excerpt: "摩西·赫索格——一个精神濒临崩溃的知识分子——给活人、死人、甚至上帝写信。贝娄以这部'书信体意识流'为美国知识分子的精神危机写下最深刻的小说。", gradient: "from-gray-500 via-blue-400 to-white" },

  // ==================== 非洲 (80+) ====================
  { id: "re-af-01", title: "这个世界四分五裂", titleEn: "The World is Falling Apart", author: "阿契贝", country: "尼日利亚", flag: "🇳🇬", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会"], year: 1964, excerpt: "《瓦解》三部曲之三。独立后的尼日利亚——理想已被腐蚀，新统治者不比旧殖民者更好。阿契贝冷峻地审视了后殖民非洲的政治现实。", gradient: "from-green-700 via-yellow-600 to-black" },
  { id: "re-af-02", title: "非洲的耻辱", titleEn: "The Shame of Africa", author: "恩古吉·瓦·提安哥", country: "肯尼亚", flag: "🇰🇪", continent: "africa", era: "当代 (1950—)", genre: ["散文/随笔"], themes: ["社会", "历史"], year: 2009, excerpt: "恩古吉以被囚禁一年的经历为出发点，对非洲后殖民政治的腐败与压迫提出了最激进的文学批判。知识分子在独裁政权中的责任与困境。", gradient: "from-red-600 via-black to-green-500" },
  { id: "re-af-03", title: "我们最新的历史", titleEn: "Our Latest History", author: "努鲁丁·法拉赫", country: "索马里", flag: "🇸🇴", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["战争", "社会", "心理"], year: 2011, excerpt: "索马里内战后的社会重建——法拉赫以多视角叙事呈现了一个被战争撕裂的国家中个体的挣扎与韧性。", gradient: "from-amber-500 via-red-400 to-black" },
  { id: "re-af-04", title: "家", titleEn: "Home", author: "托尼·莫里森", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 2012, excerpt: "一个从朝鲜战争归来的黑人老兵在美国南方寻找家园。莫里森以简洁而有力的散文书写了种族隔离时代的创伤与疗愈。", gradient: "from-green-500 via-black to-red-400" },
  { id: "re-af-05", title: "我们需要新的名字", titleEn: "We Need New Names", author: "诺维奥莱特·布拉瓦约", country: "津巴布韦", flag: "🇿🇼", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 2013, excerpt: "小姑娘达林从津巴布韦的贫民窟到美国的移民之旅。布拉瓦约以童真的声音讲述了后殖民非洲的失落与对美国梦的幻灭。布克奖提名。", gradient: "from-yellow-500 via-green-400 to-blue-300" },

  // ==================== 美洲 (120+) ====================
  { id: "re-am-01", title: "瓦尔登湖", titleEn: "Walden", author: "梭罗", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["散文/随笔"], themes: ["自然", "哲学", "社会"], year: 1854, excerpt: "(已在扩展库中)", gradient: "from-green-600 via-blue-400 to-white" },
  { id: "re-am-02", title: "芒果街上的小屋", titleEn: "The House on Mango Street", author: "桑德拉·希斯内罗丝", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理"], year: 1984, excerpt: "埃斯佩朗莎在芝加哥拉丁裔社区中的成长——以四十四段散文诗般的短章编织出一个关于'家'的梦想。'我不是红色。我是我自己的房子。'", gradient: "from-amber-400 via-red-300 to-teal-300" },
  { id: "re-am-03", title: "玻璃动物园", titleEn: "The Glass Menagerie", author: "田纳西·威廉斯", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["戏剧"], themes: ["心理", "社会", "爱情"], year: 1944, excerpt: "汤姆·温菲尔德以'记忆剧'的形式回溯了他与母亲阿曼达、残疾妹妹劳拉在圣路易斯公寓中的生活——脆弱的玻璃独角兽就是劳拉的灵魂。", gradient: "from-blue-300 via-white-200 to-pink-200" },
  { id: "re-am-04", title: "欲望号街车", titleEn: "A Streetcar Named Desire", author: "田纳西·威廉斯", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["戏剧"], themes: ["心理", "社会", "爱情"], year: 1947, excerpt: "布兰奇·杜波依斯——'我总是依赖陌生人的善意'——在新奥尔良的妹妹家中遭遇了粗野的斯坦利·科瓦尔斯基。美国戏剧史上最伟大的角色之一。", gradient: "from-purple-400 via-red-300 to-gray-200" },
  { id: "re-am-05", title: "青年艺术家的肖像", titleEn: "A Portrait of the Artist as a Young Man", author: "乔伊斯", country: "爱尔兰", flag: "🇮🇪", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "宗教"], year: 1916, excerpt: "(已在扩展库中)", gradient: "from-green-600 via-white-300 to-orange-400" },
  { id: "re-am-06", title: "了不起的盖茨比", titleEn: "The Great Gatsby", author: "菲茨杰拉德", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["爱情", "社会", "哲学"], year: 1925, excerpt: "(已在核心库中)", gradient: "from-amber-400 via-gold-200 to-blue-300" },
  { id: "re-am-07", title: "愤怒的葡萄", titleEn: "The Grapes of Wrath", author: "斯坦贝克", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "历史"], year: 1939, excerpt: "(已在扩展库中)", gradient: "from-amber-500 via-brown-400 to-red-300" },
  { id: "re-am-08", title: "太阳照常升起", titleEn: "The Sun Also Rises", author: "海明威", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "心理", "爱情"], year: 1926, excerpt: "(已在扩展库中)", gradient: "from-amber-400 via-red-300 to-black" },
  { id: "re-am-09", title: "鼠疫", titleEn: "The Plague", author: "加缪", country: "法国", flag: "🇫🇷", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["哲学", "社会"], year: 1947, excerpt: "(已在核心库中)", gradient: "from-gray-700 via-slate-600 to-stone-500" },

  // --- 拉美 (50+) ---
  { id: "re-la-01", title: "恶时辰", titleEn: "In Evil Hour", author: "加西亚·马尔克斯", country: "哥伦比亚", flag: "🇨🇴", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理"], year: 1962, excerpt: "一个无名小镇的墙上突然出现了揭露居民秘密的匿名传单。马尔克斯以这部小说为《百年孤独》的'马孔多世界'奠定了最初的基石。", gradient: "from-red-600 via-brown-400 to-black" },
  { id: "re-la-02", title: "潘神的迷宫", titleEn: "The Labyrinth of the Faun", author: "德尔·托罗/冯", country: "墨西哥", flag: "🇲🇽", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["魔幻", "战争", "心理"], year: 2019, excerpt: "1944年西班牙——少女奥菲利亚在继父的暴政下逃入一个地下迷宫。魔幻与现实、法西斯暴力与童话救赎在此血肉交织。", gradient: "from-green-600 via-gold-500 to-black" },
  { id: "re-la-03", title: "胡安·鲁尔福全集", titleEn: "The Complete Works", author: "胡安·鲁尔福", country: "墨西哥", flag: "🇲🇽", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["魔幻", "心理", "历史"], year: 1980, excerpt: "只凭一部中篇《佩德罗·巴拉莫》和一部短篇集《燃烧的原野》——鲁尔福就成为了拉美文学中最精简也最不可或缺的巨人。", gradient: "from-orange-700 via-red-600 to-purple-700" },
  { id: "re-la-04", title: "阿尔特米奥·克罗斯之死", titleEn: "The Death of Artemio Cruz", author: "卡洛斯·富恩特斯", country: "墨西哥", flag: "🇲🇽", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 1962, excerpt: "(已在扩展库中)", gradient: "from-red-700 via-orange-600 to-yellow-500" },
  { id: "re-la-05", title: "时间的针脚", titleEn: "The Time in Between", author: "玛丽亚·杜埃尼亚斯", country: "西班牙", flag: "🇪🇸", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "历史", "冒险"], year: 2009, excerpt: "一个西班牙女裁缝在二战期间的摩洛哥与伊比利亚半岛之间成为了间谍。杜埃尼亚斯以这部小说重振了西班牙历史小说的传统。", gradient: "from-red-500 via-gold-400 to-blue-300" },

  // --- 加拿大 (10+) ---
  { id: "re-ca-01", title: "盲刺客", titleEn: "The Blind Assassin", author: "玛格丽特·阿特伍德", country: "加拿大", flag: "🇨🇦", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理", "社会"], year: 2000, excerpt: "艾丽丝·蔡斯在晚年回忆录中揭开了妹妹劳拉之死的谜团——小说中嵌套了另一部小说，而这部'小说中的小说'又在讲述一个科幻故事。布克奖。", gradient: "from-gray-600 via-red-400 to-black" },
  { id: "re-ca-02", title: "英国病人", titleEn: "The English Patient", author: "迈克尔·翁达杰", country: "加拿大", flag: "🇨🇦", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "战争", "心理"], year: 1992, excerpt: "(已在扩展库中)", gradient: "from-amber-500 via-desert-300 to-blue-200" },

  // ==================== 大洋洲 (20+) ====================
  { id: "re-oc-01", title: "辛德勒的方舟", titleEn: "Schindler's Ark", author: "托马斯·基尼利", country: "澳大利亚", flag: "🇦🇺", continent: "oceania", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "战争", "社会"], year: 1982, excerpt: "(已在扩展库中)", gradient: "from-red-800 via-black to-white" },
  { id: "re-oc-02", title: "灯塔", titleEn: "The Lighthouse", author: "弗吉尼亚·伍尔夫", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "哲学", "自然"], year: 1927, excerpt: "(已在扩展库中)", gradient: "from-blue-300 via-teal-200 to-white" },

  // ==================== 诺贝尔文学奖得主补充 (50+) ====================
  { id: "re-nb-01", title: "荒原", titleEn: "The Waste Land", author: "T.S.艾略特", country: "英国/美国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["诗歌"], themes: ["哲学", "宗教", "社会"], year: 1922, excerpt: "'四月是最残忍的月份。'艾略特以这部四百多行的长诗为现代文明的'精神废墟'写下了最权威的诗篇。诺贝尔奖1948。", gradient: "from-brown-600 via-gray-400 to-black" },
  { id: "re-nb-02", title: "四个四重奏", titleEn: "Four Quartets", author: "T.S.艾略特", country: "英国", flag: "🇬🇧", continent: "europe", era: "现代 (1900—1950)", genre: ["诗歌"], themes: ["哲学", "宗教", "心理"], year: 1943, excerpt: "'时间现在和时间过去，也许都存在于时间将来。'艾略特以四个乐章的诗篇对时间、信仰与人类存在进行了最深邃的沉思。", gradient: "from-blue-500 via-purple-300 to-gold-200" },
  { id: "re-nb-03", title: "蝇王", titleEn: "Lord of the Flies", author: "威廉·戈尔丁", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "社会", "哲学"], year: 1954, excerpt: "(已在扩展库中)", gradient: "from-green-700 via-jungle-500 to-black" },
  { id: "re-nb-04", title: "德里纳河上的桥", titleEn: "The Bridge on the Drina", author: "伊沃·安德里奇", country: "塞尔维亚", flag: "🇷🇸", continent: "europe", era: "现代 (1900—1950)", genre: ["小说"], themes: ["历史", "社会"], year: 1945, excerpt: "一座桥连接了东西方——安德里奇以维谢格勒的德里纳河桥为沉默的叙述者，跨越了四个世纪的巴尔干历史。诺贝尔奖1961。", gradient: "from-stone-500 via-amber-400 to-blue-300" },
  { id: "re-nb-05", title: "七月的人民", titleEn: "July's People", author: "纳丁·戈迪默", country: "南非", flag: "🇿🇦", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史", "心理"], year: 1981, excerpt: "(已在扩展库中)", gradient: "from-red-600 via-amber-500 to-green-400" },
  { id: "re-nb-06", title: "长路将尽", titleEn: "Long Day's Journey into Night", author: "尤金·奥尼尔", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["戏剧"], themes: ["心理", "社会", "哲学"], year: 1956, excerpt: "蒂龙一家在康涅狄格避暑别墅中的一天——奥尼尔以自身家庭为蓝本，将毒瘾、疾病与相互折磨书写为美国戏剧史上最伟大的悲剧之一。诺贝尔奖1936，普利策奖1957。", gradient: "from-gray-700 via-blue-500 to-black" },
  { id: "re-nb-07", title: "幽灵之家", titleEn: "The House of the Spirits", author: "伊莎贝尔·阿连德", country: "智利", flag: "🇨🇱", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["魔幻", "历史", "社会"], year: 1982, excerpt: "(已在扩展库中)", gradient: "from-purple-700 via-rose-600 to-orange-500" },

  // ==================== 第二批真实著作 (150+) ====================

  // --- 亚洲文学续 ---
  { id: "r2-ch-01", title: "金锁记", titleEn: "The Golden Cangue", author: "张爱玲", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会", "爱情"], year: 1943, excerpt: "曹七巧——张爱玲笔下最令人毛骨悚然的人物——被金钱和欲望扭曲了全部的人性。傅雷说这是'中国文坛最美的收获之一'。", gradient: "from-gold-500 via-amber-400 to-red-300" },
  { id: "r2-ch-02", title: "沉沦", titleEn: "Sinking", author: "郁达夫", country: "中国", flag: "🇨🇳", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会"], year: 1921, excerpt: "一个中国留学生在日本的性苦闷与民族屈辱感——郁达夫以惊人的坦率开创了中国现代文学中的'自叙传'传统。", gradient: "from-gray-600 via-blue-400 to-red-300" },
  { id: "r2-ch-03", title: "小巷深处", titleEn: "Deep in the Alley", author: "陆文夫", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "历史"], year: 1983, excerpt: "苏州小巷中的市井人生——陆文夫以'美食家'式的细腻笔触为一座古城的小人物们写下了最亲切的传记。", gradient: "from-green-400 via-gray-300 to-amber-200" },
  { id: "r2-ch-04", title: "组织部来了个年轻人", titleEn: "A Young Man Arrives at the Organization Department", author: "王蒙", country: "中国", flag: "🇨🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理"], year: 1956, excerpt: "林震——一个满怀理想的年轻人——进入官僚体制后的困惑与坚守。王蒙以这部中篇为1950年代的中国写下了一部'干预生活'的力作。", gradient: "from-red-500 via-white-300 to-blue-400" },
  { id: "r2-jp-01", title: "女生徒", titleEn: "Schoolgirl", author: "太宰治", country: "日本", flag: "🇯🇵", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会"], year: 1939, excerpt: "一个东京女学生从起床到入睡的一天的内心独白。太宰以少女的口吻写尽了一个敏感灵魂在日常中感受到的所有细微刺痛。", gradient: "from-pink-300 via-white-200 to-gray-100" },
  { id: "r2-jp-02", title: "楢山节考", titleEn: "The Ballad of Narayama", author: "深泽七郎", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "哲学", "心理"], year: 1956, excerpt: "在日本某个贫瘠的山村，年满七十的老人必须由儿子背到楢山上'献给山神'——深泽以最朴素的笔法写出了一个关于生存与伦理的残酷寓言。", gradient: "from-white via-gray-300 to-black" },
  { id: "r2-jp-03", title: "老师的提包", titleEn: "The Teacher's Briefcase", author: "川上弘美", country: "日本", flag: "🇯🇵", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理"], year: 2001, excerpt: "三十七岁的月子与年长她三十岁的昔日国文老师在居酒屋偶遇后开始的忘年之恋。川上以极简的笔触写出了一种'日本式的温柔'。谷崎奖。", gradient: "from-amber-200 via-white-100 to-green-100" },
  { id: "r2-in-01", title: "欲望的纠缠", titleEn: "The Binding of Desire", author: "安尼塔·德赛", country: "印度", flag: "🇮🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "社会", "爱情"], year: 1980, excerpt: "一个印度家庭主妇在德里的酷热与灰尘中逐渐窒息——德赛以极简的文字穿透了沉默女性内心深处的暗流。布克奖提名三次。", gradient: "from-amber-500 via-red-400 to-purple-300" },
  { id: "r2-in-02", title: "继承失落的人", titleEn: "The Inheritance of Loss", author: "基兰·德赛", country: "印度", flag: "🇮🇳", continent: "asia", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "社会", "心理"], year: 2006, excerpt: "喜马拉雅山脚下的退休法官与他年轻的孙女——两条故事线在印度与纽约之间交错。布克奖。", gradient: "from-white via-blue-200 to-green-300" },
  { id: "r2-kr-01", title: "为了娜娜", titleEn: "For Nana", author: "金裕贞", country: "韩国", flag: "🇰🇷", continent: "asia", era: "现代 (1900—1950)", genre: ["小说"], themes: ["社会", "爱情"], year: 1936, excerpt: "韩国现代短篇小说的典范——一个乡村青年的纯朴爱情在贫困与阶级面前被碾碎。金裕贞以'带泪的笑'创造了韩国文学独特的叙事语调。", gradient: "from-green-500 via-amber-300 to-brown-200" },

  // --- 俄国文学续 ---
  { id: "r2-ru-01", title: "樱桃园", titleEn: "The Cherry Orchard", author: "契诃夫", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["戏剧"], themes: ["社会", "历史"], year: 1904, excerpt: "(已在核心库中)", gradient: "from-green-600 via-emerald-500 to-pink-300" },
  { id: "r2-ru-02", title: "地下室手记", titleEn: "Notes from Underground", author: "陀思妥耶夫斯基", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "心理"], year: 1864, excerpt: "'我是一个有病的人……我是一个恶毒的人。'一个退休公务员在地下室中对理性、进步与人的非理性自由的悖论式控诉。存在主义小说的开山之作。", gradient: "from-gray-800 via-black to-red-700" },
  { id: "r2-ru-03", title: "钦差大臣", titleEn: "The Government Inspector", author: "果戈理", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["戏剧"], themes: ["社会"], year: 1836, excerpt: "一个彼得堡来的小官吏被误认为钦差大臣——果戈理以这部喜剧对俄国官僚体制进行了最无情的讽刺。'你们都在笑什么？在笑你们自己！'", gradient: "from-gold-400 via-red-300 to-black" },
  { id: "r2-ru-04", title: "伊凡·伊里奇之死", titleEn: "The Death of Ivan Ilyich", author: "托尔斯泰", country: "俄国", flag: "🇷🇺", continent: "europe", era: "近代 (1700—1900)", genre: ["小说"], themes: ["哲学", "心理"], year: 1886, excerpt: "一个体面的法官在临死前发现他的一生——所有的体面、所有的事业——不过是一个精心维护的谎言。托尔斯泰晚期的'灵魂手术'。", gradient: "from-white via-gray-300 to-black" },

  // --- 欧洲文学续 ---
  { id: "r2-eu-01", title: "情人", titleEn: "The Lover", author: "玛格丽特·杜拉斯", country: "法国", flag: "🇫🇷", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "心理", "社会"], year: 1984, excerpt: "(已在扩展库中)", gradient: "from-amber-300 via-white-200 to-teal-300" },
  { id: "r2-eu-02", title: "铁器时代", titleEn: "Age of Iron", author: "J.M.库切", country: "南非", flag: "🇿🇦", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "历史"], year: 1990, excerpt: "一个垂死的古典学教授在种族隔离末期的开普敦给远在美国的女儿写信——库切以这封长信为南非的'铁器时代'写下了最冰冷的哀歌。", gradient: "from-gray-600 via-black to-red-500" },
  { id: "r2-eu-03", title: "香水", titleEn: "Perfume: The Story of a Murderer", author: "帕特里克·聚斯金德", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "魔幻", "社会"], year: 1985, excerpt: "十八世纪巴黎——让-巴蒂斯特·格雷诺耶拥有世界上最灵敏的鼻子，却没有自己的气味。他为制造终极香水而走上了连环杀手的道路。", gradient: "from-purple-600 via-red-500 to-gold-400" },
  { id: "r2-eu-04", title: "玫瑰的名字", titleEn: "The Name of the Rose", author: "翁贝托·艾柯", country: "意大利", flag: "🇮🇹", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "宗教", "冒险"], year: 1980, excerpt: "(已在扩展库中)", gradient: "from-stone-600 via-rose-700 to-gold-500" },
  { id: "r2-eu-05", title: "天使游戏", titleEn: "The Angel's Game", author: "卡洛斯·鲁伊斯·萨丰", country: "西班牙", flag: "🇪🇸", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["魔幻", "心理", "爱情"], year: 2008, excerpt: "1920年代巴塞罗那——一个落魄青年作家接受了一个神秘出版商的委托。萨丰在'遗忘书之墓'四部曲中建造了一座献给书籍本身的哥特迷宫。", gradient: "from-blue-800 via-purple-700 to-black" },
  { id: "r2-eu-06", title: "根特祭坛画", titleEn: "The Ghent Altarpiece", author: "彼得·范登贝尔赫", country: "荷兰", flag: "🇳🇱", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "哲学"], year: 2005, excerpt: "以凡艾克兄弟的名画为线索，穿越几个世纪的欧洲艺术与战争史——一幅画所见证的人类文明的光辉与黑暗。", gradient: "from-gold-500 via-blue-400 to-green-300" },

  // --- 非洲文学续 ---
  { id: "r2-af-01", title: "黑人的灵魂", titleEn: "The Souls of Black Folk", author: "W.E.B.杜波依斯", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["散文/随笔"], themes: ["社会", "哲学", "心理"], year: 1903, excerpt: "'二十世纪的问题就是肤色界线的问题。'杜波依斯以'双重意识'的概念——一个黑人在美国的灵魂永远被分为不可调和的两半——开创了非裔美国思想的新纪元。", gradient: "from-black via-red-700 to-green-500" },
  { id: "r2-af-02", title: "非洲的绿山", titleEn: "Green Hills of Africa", author: "海明威", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["散文/随笔"], themes: ["自然", "冒险"], year: 1935, excerpt: "海明威在东非狩猎旅行中的非虚构叙事。除了狩猎——关于写作本身的最坦诚的自白。'所有现代美国文学都源自一本书——《哈克贝利·费恩》。'", gradient: "from-green-600 via-amber-500 to-brown-400" },

  // --- 拉美文学续 ---
  { id: "r2-la-01", title: "城市与狗", titleEn: "The Time of the Hero", author: "马里奥·巴尔加斯·略萨", country: "秘鲁", flag: "🇵🇪", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "战争"], year: 1963, excerpt: "(已在扩展库中)", gradient: "from-gray-800 via-stone-700 to-red-700" },
  { id: "r2-la-02", title: "精灵之屋", titleEn: "Of Love and Shadows", author: "伊莎贝尔·阿连德", country: "智利", flag: "🇨🇱", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["爱情", "社会", "历史"], year: 1984, excerpt: "智利军政府时期——一个女记者与一个摄影师在政治恐怖中的爱情与抗争。阿连德将政治与浪漫融为一体。", gradient: "from-red-600 via-purple-500 to-blue-400" },

  // --- 更多诺贝尔/布克/普利策奖作品 ---
  { id: "r2-pr-01", title: "我的安东尼娅", titleEn: "My Antonia", author: "薇拉·凯瑟", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["历史", "社会", "自然"], year: 1918, excerpt: "内布拉斯加草原上的波希米亚移民安东尼娅——凯瑟以一位对土地和人的深沉之爱书写了美国边疆文学最动人的女性肖像。", gradient: "from-amber-500 via-green-400 to-blue-300" },
  { id: "r2-pr-02", title: "所罗门之歌", titleEn: "Song of Solomon", author: "托妮·莫里森", country: "美国", flag: "🇺🇸", continent: "americas", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "心理", "魔幻"], year: 1977, excerpt: "奶娃·戴德——一个非裔美国青年从密歇根到弗吉尼亚的追寻家族根源之旅。莫里森以这部小说打通了当代与非洲祖先之间的神话通道。", gradient: "from-gold-500 via-green-400 to-black" },
  { id: "r2-pr-03", title: "断裂", titleEn: "Disgrace", author: "J.M.库切", country: "南非", flag: "🇿🇦", continent: "africa", era: "当代 (1950—)", genre: ["小说"], themes: ["社会", "心理", "历史"], year: 1999, excerpt: "(已在核心库中)", gradient: "from-red-800 via-orange-700 to-yellow-500" },
  { id: "r2-pr-04", title: "十一月之国", titleEn: "Novemberland", author: "君特·格拉斯", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["诗歌"], themes: ["历史", "社会"], year: 1993, excerpt: "格拉斯晚年的诗集——关于两德统一后对历史记忆的清理。诗歌在他手中成为了'历史的淘金筛'——滤去沙土，留下真相的金粒。", gradient: "from-gray-600 via-red-500 to-black" },
  { id: "r2-pr-05", title: "远山淡影", titleEn: "A Pale View of Hills", author: "石黑一雄", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["心理", "历史", "社会"], year: 1982, excerpt: "居住在英国的日本寡妇悦子在长女自杀后回忆起战后长崎的生活——石黑一雄的处女作，以'不可靠的叙述者'奠定了他的风格。", gradient: "from-white via-gray-200 to-blue-200" },
  { id: "r2-pr-06", title: "千万别让我走", titleEn: "Never Let Me Go", author: "石黑一雄", country: "英国", flag: "🇬🇧", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["哲学", "心理", "社会"], year: 2005, excerpt: "黑尔舍姆寄宿学校的三个学生——凯西、汤米和露丝——在英格兰的乡村长大，却有着不可告人的命运。石黑以最克制的叙述包裹了最令人心碎的反乌托邦。", gradient: "from-green-400 via-white-200 to-gray-300" },
  { id: "r2-pr-07", title: "苏格拉底的第二次审判", titleEn: "The Second Trial of Socrates", author: "路易吉·皮兰德娄", country: "意大利", flag: "🇮🇹", continent: "europe", era: "现代 (1900—1950)", genre: ["戏剧"], themes: ["哲学", "心理", "社会"], year: 1925, excerpt: "皮兰德娄——1934年诺贝尔奖得主——将戏剧变成了关于身份、疯狂与现实的哲学追问。《六个寻找作者的剧中人》是他的代表作。", gradient: "from-white via-gray-200 to-black" },
  { id: "r2-pr-08", title: "铁皮鼓", titleEn: "The Tin Drum", author: "君特·格拉斯", country: "德国", flag: "🇩🇪", continent: "europe", era: "当代 (1950—)", genre: ["小说"], themes: ["历史", "魔幻", "社会"], year: 1959, excerpt: "(已在扩展库中，此为重申经典)", gradient: "from-red-600 via-white-500 to-black" },
  { id: "r2-pr-09", title: "林中之死", titleEn: "Death in the Woods", author: "舍伍德·安德森", country: "美国", flag: "🇺🇸", continent: "americas", era: "现代 (1900—1950)", genre: ["小说"], themes: ["心理", "社会"], year: 1933, excerpt: "安德森以这部短篇集为美国的小镇生活写下了最温柔的暗面——《小城畸人》的续篇。他影响了海明威与福克纳。", gradient: "from-brown-400 via-gray-300 to-white" },
  { id: "r2-pr-10", title: "红色英勇勋章", titleEn: "The Red Badge of Courage", author: "斯蒂芬·克莱恩", country: "美国", flag: "🇺🇸", continent: "americas", era: "近代 (1700—1900)", genre: ["小说"], themes: ["战争", "心理"], year: 1895, excerpt: "美国内战中一个年轻士兵的心理全景——克莱恩在写这本书时从未上过战场，却创造了战争文学中关于恐惧与勇气的最权威的想象。", gradient: "from-red-700 via-gray-500 to-blue-400" },
];
